# Generated by Django 5.2.7 on 2025-10-17 19:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0009_update_dynamic_safety_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemporaryPDF',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SituationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('pdf', models.FileField(upload_to='')),
                ('wfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.wfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(default='', max_length=6000)),
                ('cwa_center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
                ('small', models.ImageField(null=True, upload_to='')),
                ('wfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.wfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
