# Generated by Django 5.2.7 on 2025-10-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_stories_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationreport',
            name='description',
        ),
    ]
