# Generated by Django 5.2.10 on 2026-02-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx_stories_api', '0002_situation_report_delete_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situationreport',
            name='wfo',
        ),
        migrations.DeleteModel(
            name='TemporaryImage',
        ),
        migrations.DeleteModel(
            name='TemporaryPDF',
        ),
        migrations.RemoveField(
            model_name='weatherstory',
            name='wfo',
        ),
        migrations.DeleteModel(
            name='SituationReport',
        ),
        migrations.DeleteModel(
            name='WeatherStory',
        ),
    ]
