# Generated by Django 5.2.6 on 2025-09-11 03:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("spatial", "0001_initial"),
        ("spatial", "0002_weatherplace"),
        ("spatial", "0003_alter_weatherplace_table"),
        ("spatial", "0004_weathercounties"),
        ("spatial", "0005_weatherstates"),
        ("spatial", "0006_weathercountywarningareas"),
        ("spatial", "0007_weatheralertscache"),
        ("spatial", "0008_alter_weatheralertscache_alertkind_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(sql="CREATE EXTENSION IF NOT EXISTS postgis", reverse_sql="DROP EXTENSION postgis"),
        migrations.CreateModel(
            name="WeatherZone",
            fields=[
                ("id", models.CharField(max_length=45, primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=2, null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_zones_dj",
            },
        ),
        migrations.CreateModel(
            name="WeatherPlace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(null=True)),
                ("state", models.TextField(null=True)),
                ("statename", models.TextField(null=True)),
                ("statefips", models.CharField(max_length=2, null=True)),
                ("county", models.TextField(null=True)),
                ("countyfips", models.CharField(max_length=5, null=True)),
                ("timezone", models.TextField(null=True)),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_places_dj",
            },
        ),
        migrations.CreateModel(
            name="WeatherCounties",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(max_length=2, null=True)),
                ("statename", models.TextField(null=True)),
                ("statefips", models.CharField(max_length=2, null=True)),
                ("countyname", models.TextField(null=True)),
                ("countyfips", models.CharField(max_length=5, null=True)),
                ("timezone", models.TextField(null=True)),
                ("dst", models.BooleanField(null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("cwas", models.TextField(null=True)),
            ],
            options={
                "db_table": "weathergov_geo_counties_dj",
            },
        ),
        migrations.CreateModel(
            name="WeatherStates",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(max_length=2, null=True)),
                ("name", models.TextField(null=True)),
                ("fips", models.CharField(max_length=2, null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_states_dj",
            },
        ),
        migrations.CreateModel(
            name="WeatherCountyWarningAreas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wfo", models.CharField(max_length=3, null=True)),
                ("cwa", models.CharField(max_length=3, null=True)),
                ("region", models.CharField(max_length=2, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("st", models.CharField(max_length=2, null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_cwas_dj",
            },
        ),
        migrations.CreateModel(
            name="WeatherAlertsCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hash", models.TextField()),
                ("alertjson", models.TextField()),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ("alertkind", models.TextField(default=None, null=True)),
            ],
            options={
                "db_table": "weathergov_geo_alerts_cache_dj",
            },
        ),
    ]
