# Generated by Django 5.2.6 on 2025-09-11 02:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherZone",
            fields=[
                ("id", models.CharField(max_length=45, primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=2, null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_zones_dj",
            },
        ),
    ]
