# Generated by Django 5.2.6 on 2025-09-11 02:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherPlace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(null=True)),
                ("state", models.TextField(null=True)),
                ("statename", models.TextField(null=True)),
                ("statefips", models.CharField(max_length=2, null=True)),
                ("county", models.TextField(null=True)),
                ("countyfips", models.CharField(max_length=5, null=True)),
                ("timezone", models.TextField(null=True)),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
