# Generated by Django 5.2.6 on 2025-09-11 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0002_weatherplace"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="weatherplace",
            table="weathergov_geo_places_dj",
        ),
    ]
