# Generated by Django 5.2.6 on 2025-09-11 02:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0003_alter_weatherplace_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCounties",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(max_length=2, null=True)),
                ("statename", models.TextField(null=True)),
                ("statefips", models.CharField(max_length=2, null=True)),
                ("countyname", models.TextField(null=True)),
                ("countyfips", models.CharField(max_length=5, null=True)),
                ("timezone", models.TextField(null=True)),
                ("dst", models.BooleanField(null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("cwas", models.TextField(null=True)),
            ],
            options={
                "db_table": "weathergov_geo_counties_dj",
            },
        ),
    ]
