# Generated by Django 5.2.6 on 2025-09-11 03:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spatial", "0004_weathercounties"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherStates",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(max_length=2, null=True)),
                ("name", models.TextField(null=True)),
                ("fips", models.CharField(max_length=2, null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_states_dj",
            },
        ),
    ]
