# Generated by Django 5.2.6 on 2025-09-11 03:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0005_weatherstates"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherCountyWarningAreas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("wfo", models.CharField(max_length=3, null=True)),
                ("cwa", models.CharField(max_length=3, null=True)),
                ("region", models.CharField(max_length=2, null=True)),
                ("city", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("st", models.CharField(max_length=2, null=True)),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_cwas_dj",
            },
        ),
    ]
