# Generated by Django 5.2.6 on 2025-09-11 03:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spatial", "0006_weathercountywarningareas"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherAlertsCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hash", models.TextField()),
                ("alertjson", models.TextField()),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ("alertkind", models.TextField(null=True)),
            ],
            options={
                "db_table": "weathergov_geo_alerts_cache_dj",
            },
        ),
    ]
