# Generated by Django 5.2.6 on 2025-09-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0007_weatheralertscache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatheralertscache",
            name="alertkind",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterModelTable(
            name="weatheralertscache",
            table="weathergov_geo_alerts_cache_dj",
        ),
    ]
