# Generated by Django 5.2.6 on 2025-09-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0019_alter_weatheralertscache_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatheralertscache",
            name="alertjson",
            field=models.JSONField(),
        ),
    ]
