# Generated by Django 5.2.7 on 2025-10-07 19:19

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0020_alter_weatheralertscache_alertjson"),
    ]

    operations = [CreateExtension("fuzzystrmatch")]
