# Generated by Django 5.2.7 on 2025-10-08 14:48

from django.db import migrations, models
# import spatial.models as spatial


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0021_install_fuzzystrmatch_extension_20251007_1919"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSpatialMetadata",
            fields=[
                ("table", models.TextField(primary_key=True, serialize=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "weathergov_geo_metadata",
            },
        ),
    ]
