# Generated by Django 5.2.7 on 2025-10-22 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0023_initial_spatial_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercounties',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counties', to='spatial.weatherstates'),
        ),
    ]
