# Generated by Django 5.2.7 on 2025-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    def truncate_alert_cache(apps, schema):
        apps.get_model("spatial","weatheralertscache").objects.truncate()

    dependencies = [
        ('spatial', '0024_alter_weathercounties_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheralertscache',
            name='counties',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatheralertscache',
            name='states',
            field=models.JSONField(default='[]'),
            preserve_default=False,
        ),
    ]
