# Generated by Django 5.2.7 on 2025-10-24 15:21

import django.core.validators
import django.db.models.deletion
from django.core.exceptions import ValidationError
from django.db import migrations, models
from spatial.management.commands._spatial_util import COUNTY_FIPS_TO_PRIMARY_WFO_MAP

class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0025_weatheralertscache_counties_and_more'),
    ]

    def set_primary_wfo(apps, schema):
        # Clear the alert cache. This should have been done in the previous
        # migration, but it wasn't. As long as it happens whenever this batch
        # of changes is pushed to beta, it doesn't matter what order it happens
        # in, so we can smoosh it in here.
        apps.get_model("spatial","weatheralertscache").objects.all().delete()

        cwas = apps.get_model("spatial", "WeatherCountyWarningAreas")

        counties = apps.get_model("spatial","WeatherCounties").objects.all()
        for county in counties:
            # If a county only has one WFO, that is the primary.
            if county.cwas.count() == 1:
                county.primarywfo = county.cwas.all()[0]
            # Otherwise, we lookup the primary in our mapping.
            elif county.countyfips in COUNTY_FIPS_TO_PRIMARY_WFO_MAP:
                county.primarywfo = cwas.objects.get(wfo=COUNTY_FIPS_TO_PRIMARY_WFO_MAP[county.countyfips])
            else:
                raise ValidationError(f"County FIPS {county.countyfips} has no associated CWAs")
            county.save()

    operations = [
        migrations.RemoveField(
            model_name='weathercounties',
            name='cwastring',
        ),
        # Initially allow the primary WFO to be null
        migrations.AddField(
            model_name='weathercounties',
            name='primarywfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_counties', to='spatial.weathercountywarningareas',null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_primary_wfo),
        # After updating all the fields, make it not null.
        migrations.AlterField(
            model_name='weathercounties',
            name='primarywfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_counties', to='spatial.weathercountywarningareas',null=False),
        ),
    ]
