# Generated by Django 5.2.7 on 2025-10-29 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0026_add_primary_wfo_to_county"),
    ]

    operations = [
        # For counties that are only associated with a single WFO, we can set
        # their primary WFO directly in a one-shot query.
        migrations.RunSQL(
            """
            UPDATE weathergov_geo_counties
            SET timezone='Pacific/Honolulu'
            WHERE timezone='Pacific/Hololulu'
            """
        ),
    ]
