# Generated by Django 5.2.9 on 2026-01-06 17:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0028_weathercounties_countyfips_as_unique_and_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatheralertscache",
            name="shape_simplified",
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
        migrations.RunSQL(
            """
            TRUNCATE TABLE weathergov_geo_alerts_cache
            """
        ),
    ]
