# Generated by Django 5.2.9 on 2026-01-15 05:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0029_store_alert_simplified_geometry_separately"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            TRUNCATE TABLE weathergov_geo_alerts_cache
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
