# Generated by Django 5.2.10 on 2026-01-26 16:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0030_truncate_alert_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastGridPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('wfo', models.CharField(max_length=3)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'weathergov_ndfd_gridpoints',
                'unique_together': {('x', 'y', 'wfo')},
            },
        ),
        migrations.CreateModel(
            name='ForecastGridLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grid_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='spatial.forecastgridpoints')),
            ],
            options={
                'db_table': 'weathergov_ndfd_grid_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
