# Generated by Django 5.2.10 on 2026-01-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0031_forecastgridpoints_forecastgridlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastGridHeatIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interval_start", models.DateTimeField(db_index=True)),
                ("wfo", models.CharField(max_length=3)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("hit_count", models.IntegerField()),
                ("relative_heat", models.FloatField()),
                ("cache_radius", models.IntegerField()),
            ],
            options={
                "db_table": "weathergov_ndfd_grid_index",
                "ordering": ["-interval_start"],
                "unique_together": {("interval_start", "wfo", "x", "y")},
            },
        ),
    ]
