# Generated by Django 6.0.3 on 2026-04-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0032_forecastgridheatindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherstates",
            name="county_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weatherstates",
            name="timezone",
            field=models.TextField(null=True),
        ),
    ]
