# Generated by Django 6.0.3 on 2026-05-06 15:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0033_add_county_counts_and_timezones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weatherstates",
            name="county_count",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="WeatherGridPoints",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cwa", models.CharField(max_length=3)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("point", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "db_table": "weathergov_geo_gridpoints",
                "indexes": [models.Index(fields=["x", "y"], name="weathergov__x_381185_idx")],
            },
        ),
    ]
