# Generated by Django 6.0.3 on 2026-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0034_alter_weatherstates_county_count_weathergridpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathergridpoints',
            name='is_marine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weathergridpoints',
            name='type',
            field=models.CharField(default='land', max_length=255),
        ),
        migrations.AddIndex(
            model_name='weathergridpoints',
            index=models.Index(fields=['x', 'y', 'cwa'], name='weathergov__x_12cabd_idx'),
        ),
    ]
