# Generated by Django 6.0.5 on 2026-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0035_weathergridpoints_is_marine_weathergridpoints_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathergridpoints',
            name='is_marine',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='weathergridpoints',
            name='type',
            field=models.CharField(default='land', max_length=255, null=True),
        ),
    ]
