# Generated by Django 6.0.5 on 2026-06-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0036_alter_weathergridpoints_is_marine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherzone',
            name='wfo',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
