# Generated by Django 6.0.5 on 2026-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0037_weatherzone_wfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathergridpoints',
            name='is_marine',
            field=models.BooleanField(default=False),
        ),
    ]
