# Generated by Django 6.0.3 on 2026-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0038_alter_weathergridpoints_is_marine'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercounties',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
