# Generated by Django 6.0.5 on 2026-06-01 19:23

from django.db import migrations
from django.contrib.postgres.indexes import GistIndex
from django.db.models import Func


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0039_add_county_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="weathergridpoints",
            index=GistIndex(
                Func("point", template="%(expressions)s::geography"),
                name="weathergov_geo_grid_geog_idx",
            ),
        ),
    ]
