# Generated by Django 6.0.5 on 2026-06-03 16:51

from django.db import migrations
from django.contrib.postgres.indexes import GistIndex
from django.db.models import Func


class Migration(migrations.Migration):
    dependencies = [
        ("spatial", "0040_add_spatial_geography_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="weatheralertscache",
            index=GistIndex(
                Func("shape_simplified", template="%(expressions)s::geography"),
                name="weathergov_alerts_geog_idx",
            ),
        ),
    ]
