# Generated by Django 6.0.5 on 2026-07-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration): # noqa: D101

    dependencies = [
        ("spatial", "0041_add_alerts_geography_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherzone",
            name="name",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
