# Generated by Django 6.0.5 on 2026-07-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0042_weatherzone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPCProbabilisticPrecip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfo', models.CharField(max_length=3)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('cycle', models.DateTimeField()),
                ('valid_time', models.DateTimeField()),
                ('rain_data', models.JSONField(null=True)),
                ('snow_data', models.JSONField(null=True)),
                ('freezing_rain_data', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weathergov_wpc_prob_precip',
            },
        ),
        migrations.AddIndex(
            model_name='wpcprobabilisticprecip',
            index=models.Index(fields=['wfo', 'x', 'y'], name='weathergov__wfo_7ee9f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wpcprobabilisticprecip',
            unique_together={('wfo', 'x', 'y')},
        ),
    ]
