# Generated by Django 6.0.5 on 2026-08-26 14:46

from django.db import migrations


class Migration(migrations.Migration):  # noqa: D101

    dependencies = [
        ("spatial", "0043_wpcprobabilisticprecip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weathergridpoints",
            name="is_marine",
        ),
        migrations.RemoveField(
            model_name="weathergridpoints",
            name="type",
        ),
    ]
