# Generated by Django 6.0.5 on 2026-09-03 22:40

import django.contrib.postgres.fields
import spatial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0044_remove_weathergridpoints_is_marine_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wpcprobabilisticprecip',
            name='weathergov__wfo_7ee9f8_idx',
        ),
        migrations.RemoveField(
            model_name='wpcprobabilisticprecip',
            name='freezing_rain_data',
        ),
        migrations.RemoveField(
            model_name='wpcprobabilisticprecip',
            name='rain_data',
        ),
        migrations.RemoveField(
            model_name='wpcprobabilisticprecip',
            name='snow_data',
        ),
        migrations.RemoveField(
            model_name='wpcprobabilisticprecip',
            name='valid_time',
        ),
        migrations.AddField(
            model_name='wpcprobabilisticprecip',
            name='freezing_rain_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=spatial.models.RealField(), null=True),
        ),
        migrations.AddField(
            model_name='wpcprobabilisticprecip',
            name='rain_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=spatial.models.RealField(), null=True),
        ),
        migrations.AddField(
            model_name='wpcprobabilisticprecip',
            name='snow_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=spatial.models.RealField(), null=True),
        ),
        migrations.AddField(
            model_name='wpcprobabilisticprecip',
            name='valid_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=[]),
            preserve_default=False,
        ),
    ]
