spec:
  # these inputs permit flexible pipeline runs from the GitLab UI
  inputs:
    build-images:
      type: boolean
      default: true
      description: "Build Docker images containing 3rd party dependencies using the config files on the selected branch. Images are tagged with the branch slug and pushed to the NOAA GitLab container registry."
    run-django-ci:
      type: boolean
      default: true
      description: "Lint and test Django in the selected branch using config from that branch. Uses dependencies from main, unless `build-images` is true."
    run-js-ci:
      type: boolean
      default: true
      description: "Lint and test JS in the selected branch using config from that branch. Uses dependencies from main, unless `build-images` is true."
---
# NB: this file is less confusing to read once you realize that it does
#     different things, depending on which branch is in the pipeline

stages:
  - gather  # gather the 3rd party dependencies and push images of them to the registry
  - build   # pull the dependency images, put the code in them, push the code images
  - lint    # pull the code images and lint
  - test    # pull the code images and test

# these are available in all the running containers (images and services)
variables:
  POSTGRES_USER: drupal
  POSTGRES_PASSWORD: drupal
  POSTGRES_DB: weathergov
  USE_TAG: main  # in a typical pipeline run, use dependency images built on main

# control when pipelines run and override some parameters
workflow:
  rules:
    # when building from the GitLab UI, use dependency images built on the current branch
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.build-images ]]" == "true"
      variables:
        USE_TAG: $CI_COMMIT_REF_SLUG
    # always allow CI pipelines on pushes and from UI -- nb: a merge will cause a push to the target branch
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push"

# common config for using Docker in later jobs
.docker-in-docker:
  image: docker:27
  services:
    - name: docker:27-dind
      command: [ "--tls=false" ]
      variables:
        HEALTHCHECK_TCP_PORT: "2375"
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

# common config for building images using a specified Dockerfile in the repo
.build-dependencies-image:
  extends: .docker-in-docker
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -f ${BUILD_CONTEXT}${DOCKERFILE} -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG $BUILD_CONTEXT
  - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG

# common config for building images using a Dockerfile passed inline as a variable
.build-image:
  extends: .docker-in-docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      cat > Dockerfile.tmp << EOF
      $DOCKERFILE
      EOF
    - cat Dockerfile.tmp
    - docker build -f Dockerfile.tmp -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG $BUILD_CONTEXT
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG

# build a base image with all the current node_modules and other JavaScript dependencies
gather-forecast-node-dependencies:
  extends: .build-dependencies-image
  stage: gather
  variables:
    BUILD_CONTEXT: ./
    DOCKERFILE: Dockerfile.node.ci
    IMAGE_NAME: node-with-deps
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_SLUG == "main"
      changes:
        - Dockerfile.node.ci
        - package.json
        - package-lock.json
        - api-interop-layer/package.json
        - api-interop-layer/package-lock.json
        - tests/api/package.json
        - tests/api/package-lock.json
        - spatial-data/package.json
        - spatial-data/package-lock.json
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.build-images ]]" == "true"

# # build a base image with all the current Python dependencies
gather-forecast-django-dependencies:
  extends: .build-dependencies-image
  stage: gather
  variables:
    BUILD_CONTEXT: forecast/
    DOCKERFILE: Dockerfile.ci
    IMAGE_NAME: python-with-deps
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_SLUG == "main"
      changes:
        - forecast/Dockerfile.ci
        - forecast/requirements.txt
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.build-images ]]" == "true"

# # lint all JavaScript in the repo in one job
js-lint:
  stage: lint
  needs:
    - job: gather-forecast-node-dependencies
      optional: true
  image: $CI_REGISTRY_IMAGE/node-with-deps:$USE_TAG
  script:
    # NB: GitLab clones into CI_BUILDS_DIR which defaults to
    # /builds/gitlab-licensed/NWS/Systems/DIS/Weather.gov-2.0/ whereas in our Docker
    # images our WORKDIR is /app. so we symlink the various /app/node_modules to
    # CI_BUILDS_DIR so we can "npm run" as needed.
    - ln -s /app/node_modules/ .
    - ln -s /app/api-interop-layer/node_modules api-interop-layer/
    - ln -s /app/tests/api/node_modules tests/api/
    - npx eslint
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.run-js-ci ]]" == "true"

django-lint:
  stage: lint
  needs:
    - job: gather-forecast-django-dependencies
      optional: true
  image: $CI_REGISTRY_IMAGE/python-with-deps:$USE_TAG
  script:
    - cd forecast/
    - python -m ruff check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.run-django-ci ]]" == "true"

django-test:
  stage: test
  needs:
    - job: gather-forecast-django-dependencies
      optional: true
  image: $CI_REGISTRY_IMAGE/python-with-deps:$USE_TAG
  services:
  - name: postgis/postgis:17-3.5
    alias: database
    variables:
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      POSTGRES_DB: weathergov
  script:
    - cd forecast/
    - ldconfig -p | grep gdal
    - pip install coverage
    - python manage.py migrate
    - coverage run manage.py test
    - coverage xml -o coverage.xml
    - coverage report
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: forecast/coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.run-django-ci ]]" == "true"

web-component-and-interop-test:
  stage: test
  needs:
    - job: gather-forecast-node-dependencies
      optional: true
  image: $CI_REGISTRY_IMAGE/node-with-deps:$USE_TAG
  script:
    # NB: GitLab clones into CI_BUILDS_DIR which defaults to
    # /builds/gitlab-licensed/NWS/Systems/DIS/Weather.gov-2.0/ whereas in our Docker
    # images our WORKDIR is /app. so we symlink the various /app/node_modules to
    # CI_BUILDS_DIR so we can "npm run" as needed.
    - ln -s /app/node_modules/ .
    - ln -s /app/api-interop-layer/node_modules api-interop-layer/
    - ln -s /app/tests/api/node_modules tests/api/
    - npx c8 --reporter cobertura -o coverage/wc/ --reporter text-summary  mocha --require forecast/frontend/tests/components/preload.js forecast/frontend/tests/components/*-tests.js
    # We also do interop layer tests at the same time so we don't have to wait
    # for another runner to come available.
    - cd api-interop-layer
    - npx c8 --reporter cobertura -o ../coverage/interop/ --reporter text-summary mocha '**/*.test.js' --exclude 'node_modules/**' --require mocha.js
  coverage:
    /^Statements\s*:\s*([^%]+)/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/*/cobertura-coverage.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web" && "$[[ inputs.run-js-ci ]]" == "true"
