FROM mcr.microsoft.com/playwright:v1.59.1-noble

RUN mkdir -p /app

WORKDIR /app

ADD ./package.json .
ADD ./package-lock.json .

RUN npm ci --dev && \
  npx playwright install msedge && \
  npx playwright install chrome
