name: weathergov-django

services:
  database:
    image: mysql:8.0 # 8.0.35 in prod
    networks:
      - weather.gov
    volumes:
      - ./data/db:/data
    environment:
      MYSQL_DATABASE: weathergov
      MYSQL_PASSWORD: drupal
      MYSQL_USER: drupal
      MYSQL_ROOT_PASSWORD: drupal
    ports:
      - 3306:3306

  web:
    build: forecast/
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./forecast:/code
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: weathergov
      MYSQL_USER: root
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal
      INTEROP_URL: "http://api-interop-layer:8082/"
      API_URL: "http://api-proxy:8081/"
    networks:
      - weather.gov
    depends_on:
      - database
      - api-proxy
      - api-interop-layer
    links:
      - database

  api-proxy:
    build:
      context: ./tests/api
      dockerfile: Dockerfile
    environment:
      WX_NOW_TIMESTAMP: ${WX_NOW_TIMESTAMP:-}
      API_URL: "http://api-proxy:8081/"
    networks:
      - weather.gov
    ports:
      - 8081:8081
    volumes:
      - ./tests/api:/app
      - /app/node_modules


  api-interop-layer:
    build:
      context: ./api-interop-layer
      dockerfile: Dockerfile
    # Use the same resource limits as deployed
    deploy:
      resources:
        limits:
          memory: 256MB
    environment:
      PORT: 8082
      DB_NAME: weathergov
      DB_USERNAME: drupal
      DB_PASSWORD: drupal
      DB_HOST: database
      DB_PORT: 3306
      API_URL: http://api-proxy:8081
      API_INTEROP_NAME: ${API_INTEROP_NAME:-local}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE:-}
    networks:
      - weather.gov
    links:
      - database
      - api-proxy
    ports:
      - 8082:8082
      - 9229:9229
    volumes:
      - ./api-interop-layer:/app
      - /app/node_modules

  uswds:
    build:
      context: ./
      dockerfile: Dockerfile.uswds
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    

  spatial:
    build:
      context: ./spatial-data
      dockerfile: Dockerfile.spatial
    image: 18f-spatial-node:20
    networks:
      - weather.gov
    links:
      - database
    environment:
      DB_HOST: database
    volumes:
      - ./spatial-data/:/app
      - /app/node_modules

  playwright:
    build:
      dockerfile: Dockerfile.playwright
    networks:
      - weather.gov
    depends_on:
      - web
      - api-proxy
    links:
      - web
    volumes:
      - ./tests/:/app/tests
    environment:
      API_URL: http://api-proxy:8081
      WEB_URL: http://web:8080
      INTEROP_URL: http://api-interop-layer:8082
      CI: true

networks:
  weather.gov:
