FROM node:20

RUN mkdir /app
WORKDIR /app

ADD ./package.json .
ADD ./package-lock.json .
ADD ./playwright.config.js .
RUN mkdir tests
RUN npm ci
RUN npx playwright install chromium --with-deps --only-shell
CMD npx playwright test  --project chromium-e2e