services:
  database:
    platform: linux/amd64
    image: postgis/postgis:17-3.5
    networks:
      - weather.gov
    environment:
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      POSTGRES_DB: weathergov
    ports:
      - 5432:5432

  web:
    image: $ci_registry_image/web:$ci_commit_ref_slug
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: weathergov
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      INTEROP_URL: "http://api-interop-layer:8082/"
      API_URL: "http://api-proxy:8081/"
    networks:
      - weather.gov
    depends_on:
      - database
      - api-proxy
      - api-interop-layer
    links:
      - database

  api-proxy:
    image: $ci_registry_image/api-proxy:$ci_commit_ref_slug
    environment:
      WX_NOW_TIMESTAMP: ${WX_NOW_TIMESTAMP:-}
      API_URL: "http://api-proxy:8081/"
    networks:
      - weather.gov
    ports:
      - 8081:8081

  api-interop-layer:
    image: $ci_registry_image/api-interop-layer:$ci_commit_ref_slug
    environment:
      PORT: 8082
      DB_NAME: weathergov
      DB_USERNAME: drupal
      DB_PASSWORD: drupal
      DB_HOST: database
      DB_PORT: 5432
      API_URL: http://api-proxy:8081
      API_INTEROP_NAME: ${API_INTEROP_NAME:-local}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE:-}
    networks:
      - weather.gov
    links:
      - database
      - api-proxy
    ports:
      - 8082:8082
      - 9229:9229

  playwright:
    image: $ci_registry_image/utility-node:$ci_commit_ref_slug
    networks:
      - weather.gov
    depends_on:
      - web
      - api-proxy
    links:
      - web
    environment:
      API_URL: http://api-proxy:8081
      WEB_URL: http://web:8080
      INTEROP_URL: http://api-interop-layer:8082
      CI: true

networks:
  weather.gov:
