name: weathergov-django

volumes:
  postgres_data:

services:
  database:
    platform: linux/amd64
    image: postgis/postgis:17-3.5
    command: -c "max_connections=400"
    networks:
      - weather.gov
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      POSTGRES_DB: weathergov
    ports:
      - 5432:5432

  web:
    build:
      context: forecast/
      dockerfile: Dockerfile.dev
    command: gunicorn -c gunicorn.conf.py --bind 0.0.0.0:8080
    volumes:
      - ./forecast:/code
    ports:
      - 8080:8080
      - 34235:34235
    environment:
      ENABLE_DJANGO_DEBUG_TOOLBAR: false
      POSTGRES_DB: weathergov
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      INTEROP_URL: "http://api-interop-layer:8082/"
      API_URL: "http://api-proxy:8081/"
      GHWO_URL: "http://api-proxy:8081/"
      DEBUG_PORT: 34235
      DJANGO_SETTINGS_MODULE: backend.config.settings.dev
      ENABLE_OPENTELEMETRY: true
      TRACE_TEMPLATES: true # this can be noisy
      OTEL_SERVICE_NAME: "weathergov-django"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
      OTEL_PYTHON_DJANGO_TRACED_REQUEST_ATTRS: "path_info,content_type"
      WEB_GEVENT_WORKERS: 4
      WEB_INSTANCES: 1
      # the default database has max_connections=100 so we divide this between
      # web and interop, keeping in mind some connections are reserved.
      WEB_DB_MAX_CONNECTIONS: 195
    networks:
      - weather.gov
    depends_on:
      - database
      - api-proxy
      - api-interop-layer
    links:
      - database

  api-proxy:
    build:
      context: ./api-proxy
      dockerfile: Dockerfile.dev
    environment:
      WX_NOW_TIMESTAMP: ${WX_NOW_TIMESTAMP:-}
    networks:
      - weather.gov
    ports:
      - 8081:8081
      - 9230:9230
    volumes:
      - ./api-proxy:/app
      - /app/node_modules

  api-interop-layer:
    build:
      context: ./api-interop-layer
      dockerfile: Dockerfile.dev
    # Use the same resource limits as deployed
    deploy:
      resources:
        limits:
          memory: 1024MB
    environment:
      PORT: 8082
      DB_NAME: weathergov
      DB_USERNAME: drupal
      DB_PASSWORD: drupal
      DB_HOST: database
      DB_PORT: 5432
      API_URL: ${API_URL:-http://api-proxy:8081}
      GHWO_URL: ${GHWO_URL:-http://api-proxy:8081}
      SATELLITE_URL: ${SATELLITE_URL:-http://api-proxy:8081}
      RADAR_URL: ${RADAR_URL:-http://api-proxy:8081}
      API_KEY: ${API_KEY:-}
      DISABLE_GRID_ANALYSIS: ${DISABLE_GRID_ANALYSIS:-false}
      API_INTEROP_NAME: ${API_INTEROP_NAME:-local}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY:-}
      LOG_LEVEL: trace
      # TRUNCATE_HAZARD_OUTLOOKS: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ixu3N02Xp3uRPDcuZCmKIWZyNb
      # MAX_OPEN_CONNECTIONS: 0
      DISABLE_REDIS: false
      # The number of Client instances to create.
      # When set to null, the Pool instance will create
      # an unlimited amount of Client instances.
      INTEROP_API_POOL_CONNECTIONS: 20
      # The amount of time before a Client instance is removed
      # from the Pool and closed.
      # When set to null, Client instances will not be
      # removed or closed based on age.
      # INTEROP_API_POOL_CLIENT_TTL:
      # The timeout, in milliseconds, after which a socket without
      # active requests will time out.
      # Monitors time between activity on a connected socket.
      # This value may be overridden by keep-alive hints from the server.
      # INTEROP_API_POOL_KEEP_ALIVE_TIMEOUT:
      # The timeout after which a request will time out, in milliseconds.
      # Monitors time between receiving body data.
      # Use 0 to disable it entirely. Defaults to 300 seconds.
      # Please note the timeout will be reset if you keep writing data to the socket everytime.
      # INTEROP_API_POOL_BODY_TIMEOUT:
      # The amount of time, in milliseconds, the parser will wait to
      # receive the complete HTTP headers while not sending the request.
      # Defaults to 300 seconds.
      # INTEROP_API_POOL_HEADERS_TIMEOUT:
      OTEL_SERVICE_NAME: "weathergov-api-interop"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4318"
      # the default database has max_connections=100 so we divide this between
      # interop and web, keeping in mind some connections are reserved.
      API_DB_MAX_CONNECTIONS: 195
      API_INTEROP_INSTANCES: 1
    networks:
      - weather.gov
    links:
      - database
      - api-proxy
    ports:
      - 8082:8082
      - 9229:9229
    volumes:
      - ./api-interop-layer:/app
      - /app/node_modules

  uswds:
    build:
      context: ./
      dockerfile: Dockerfile.uswds.dev
    volumes:
      - ./forecast/frontend/:/app
      - /app/node_modules
    profiles: ["utility"]

  spatial:
    build:
      context: ./spatial-data
      dockerfile: Dockerfile.spatial.dev
    networks:
      - weather.gov
    links:
      - database
    environment:
      DB_HOST: database
    volumes:
      - ./spatial-data/:/app
      - /app/node_modules

  playwright:
    build:
      dockerfile: Dockerfile.node
      target: playwright
    networks:
      - weather.gov
    depends_on:
      - web
      - api-proxy
    volumes:
      - ./api-proxy/:/app/api-proxy
      - ./tests/:/app/tests
      - ./playwright.config.js:/app/playwright.config.js
      - ./reports:/reports
    environment:
      API_URL: http://api-proxy:8081
      WEB_URL: http://web:8080
      #API_URL: https://api-proxy-weathergov-test.app.cloud.gov
      #WEB_URL: https://weathergov-test.app.cloud.gov
    profiles: ["utility"]

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: node
    networks:
      - weather.gov
    volumes:
      - ./reports:/reports
      - /app/node_modules
    profiles: ["utility"]

  plantuml:
    image: plantuml/plantuml-server:tomcat
    ports:
      - 8180:8080
    profiles: ["utility"]

  redis:
    image: redis:8.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel verbose --requirepass ixu3N02Xp3uRPDcuZCmKIWZyNb
    volumes:
      - ./redis-data:/redis-data
    networks:
      - weather.gov

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.16.0
    ports:
      - 16686:16686 # UI
      - 4318:4318 # opentelemetry HTTP receiver
    networks:
      - weather.gov

networks:
  weather.gov:
