from backend.models import Region, WFO

print("Deleting existing WFOs and Regions...")
WFO.objects.all().delete()
Region.objects.all().delete()

print("Creating Regions...")
pacific = Region.objects.create(name="Pacific Region", weight=100)
central = Region.objects.create(name="Central Region", weight=98)
eastern = Region.objects.create(name="Eastern Region", weight=99)
southern = Region.objects.create(name="Southern Region", weight=0)
western = Region.objects.create(name="Western Region", weight=102)
alaska = Region.objects.create(name="Alaska Region", weight=0)

print("Creating WFOs...")
WFO.objects.create(name="Pago Pago", weight=0, code="PPG", region=pacific)
WFO.objects.create(name="Honolulu", weight=1, code="HFO", region=pacific)
WFO.objects.create(name="Guam", weight=0, code="GUM", region=pacific)
WFO.objects.create(name="Green Bay", weight=15, code="GRB", region=central)
WFO.objects.create(name="Omaha/Valley", weight=26, code="OAX", region=central)
WFO.objects.create(name="Springfield", weight=33, code="SGF", region=central)
WFO.objects.create(name="Twin Cities/Chanhassen", weight=36, code="MPX", region=central)
WFO.objects.create(name="Paducah", weight=27, code="PAH", region=central)
WFO.objects.create(name="Cheyenne", weight=2, code="CYS", region=central)
WFO.objects.create(name="Riverton", weight=31, code="RIW", region=central)
WFO.objects.create(name="Marquette", weight=22, code="MQT", region=central)
WFO.objects.create(name="North Platte", weight=24, code="LBF", region=central)
WFO.objects.create(name="Gaylord", weight=9, code="APX", region=central)
WFO.objects.create(name="Louisville", weight=21, code="LMK", region=central)
WFO.objects.create(name="Topeka", weight=35, code="TOP", region=central)
WFO.objects.create(name="Sioux Falls", weight=32, code="FSD", region=central)
WFO.objects.create(name="Aberdeen", weight=0, code="ABR", region=central)
WFO.objects.create(name="Detroit/Pontiac", weight=6, code="DTX", region=central)
WFO.objects.create(name="La Crosse", weight=20, code="ARX", region=central)
WFO.objects.create(name="Bismarck", weight=1, code="BIS", region=central)
WFO.objects.create(name="Chicago", weight=3, code="LOT", region=central)
WFO.objects.create(name="Grand Forks", weight=13, code="FGF", region=central)
WFO.objects.create(name="Milwaukee/Sullivan", weight=23, code="MKX", region=central)
WFO.objects.create(name="Grand Junction", weight=14, code="GJT", region=central)
WFO.objects.create(name="Indianapolis", weight=17, code="IND", region=central)
WFO.objects.create(name="Rapid City", weight=30, code="UNR", region=central)
WFO.objects.create(name="Des Moines", weight=5, code="DMX", region=central)
WFO.objects.create(name="Wichita", weight=37, code="ICT", region=central)
WFO.objects.create(name="Dodge City", weight=7, code="DDC", region=central)
WFO.objects.create(name="Hastings", weight=16, code="GID", region=central)
WFO.objects.create(name="Kansas City/Pleasant Hill", weight=19, code="EAX", region=central)
WFO.objects.create(name="Jackson", weight=18, code="JKL", region=central)
WFO.objects.create(name="Duluth", weight=8, code="DLH", region=central)
WFO.objects.create(name="St Louis", weight=34, code="LSX", region=central)
WFO.objects.create(name="Northern Indiana", weight=25, code="IWX", region=central)
WFO.objects.create(name="Quad Cities", weight=29, code="DVN", region=central)
WFO.objects.create(name="Grand Rapids", weight=11, code="GRR", region=central)
WFO.objects.create(name="Denver/Boulder", weight=4, code="BOU", region=central)
WFO.objects.create(name="Goodland", weight=10, code="GLD", region=central)
WFO.objects.create(name="Pueblo", weight=28, code="PUB", region=central)
WFO.objects.create(name="Lincoln", weight=12, code="ILX", region=central)
WFO.objects.create(name="Wakefield", weight=19, code="AKQ", region=eastern)
WFO.objects.create(name="Burlington", weight=6, code="BTV", region=eastern)
WFO.objects.create(name="Caribou", weight=7, code="CAR", region=eastern)
WFO.objects.create(name="Buffalo", weight=5, code="BUF", region=eastern)
WFO.objects.create(name="Columbia", weight=10, code="CAE", region=eastern)
WFO.objects.create(name="Charleston", weight=0, code="CHS", region=eastern)
WFO.objects.create(name="Newport/Morehead City", weight=14, code="MHX", region=eastern)
WFO.objects.create(name="New York City", weight=15, code="OKX", region=eastern)
WFO.objects.create(name="Cleveland", weight=9, code="CLE", region=eastern)
WFO.objects.create(name="Charleston", weight=8, code="RLX", region=eastern)
WFO.objects.create(name="Baltimore MD/Washington", weight=1, code="LWX", region=eastern)
WFO.objects.create(name="Greenville-Spartanburg", weight=12, code="GSP", region=eastern)
WFO.objects.create(name="Blacksburg", weight=3, code="RNK", region=eastern)
WFO.objects.create(name="Wilmington", weight=20, code="ILN", region=eastern)
WFO.objects.create(name="State College", weight=18, code="CTP", region=eastern)
WFO.objects.create(name="Boston/Norton", weight=4, code="BOX", region=eastern)
WFO.objects.create(name="Raleigh", weight=17, code="RAH", region=eastern)
WFO.objects.create(name="Gray", weight=11, code="GYX", region=eastern)
WFO.objects.create(name="Pittsburgh", weight=16, code="PBZ", region=eastern)
WFO.objects.create(name="Albany", weight=0, code="ALY", region=eastern)
WFO.objects.create(name="Wilmington, NC", weight=20, code="ILM", region=eastern)
WFO.objects.create(name="Binghamton", weight=2, code="BGM", region=eastern)
WFO.objects.create(name="Mount Holly", weight=13, code="PHI", region=eastern)
WFO.objects.create(name="Norman", weight=0, code="OUN", region=southern)
WFO.objects.create(name="Mobile", weight=0, code="MOB", region=southern)
WFO.objects.create(name="San Juan", weight=0, code="SJU", region=southern)
WFO.objects.create(name="Lubbock", weight=0, code="LUB", region=southern)
WFO.objects.create(name="Key West", weight=0, code="KEY", region=southern)
WFO.objects.create(name="Corpus Christi", weight=0, code="CRP", region=southern)
WFO.objects.create(name="Miami", weight=0, code="MFL", region=southern)
WFO.objects.create(name="Tallahassee", weight=0, code="TAE", region=southern)
WFO.objects.create(name="New Orleans/Baton Rouge", weight=0, code="LIX", region=southern)
WFO.objects.create(name="Morristown", weight=0, code="MRX", region=southern)
WFO.objects.create(name="Austin/San Antonio", weight=0, code="EWX", region=southern)
WFO.objects.create(name="Brownsville", weight=0, code="BRO", region=southern)
WFO.objects.create(name="Houston/Galveston", weight=0, code="HGX", region=southern)
WFO.objects.create(name="Amarillo", weight=0, code="AMA", region=southern)
WFO.objects.create(name="Huntsville", weight=0, code="HUN", region=southern)
WFO.objects.create(name="Memphis", weight=0, code="MEG", region=southern)
WFO.objects.create(name="Peachtree City", weight=0, code="FFC", region=southern)
WFO.objects.create(name="Forth Worth/Dallas", weight=0, code="FWD", region=southern)
WFO.objects.create(name="Midland/Odessa", weight=0, code="MAF", region=southern)
WFO.objects.create(name="Birmingham", weight=0, code="BMX", region=southern)
WFO.objects.create(name="Tulsa", weight=0, code="TSA", region=southern)
WFO.objects.create(name="Tampa", weight=0, code="TBW", region=southern)
WFO.objects.create(name="Nashville", weight=0, code="OHX", region=southern)
WFO.objects.create(name="Jacksonville", weight=0, code="JAX", region=southern)
WFO.objects.create(name="San Angelo", weight=0, code="SJT", region=southern)
WFO.objects.create(name="Little Rock", weight=0, code="LZK", region=southern)
WFO.objects.create(name="El Paso", weight=0, code="EPZ", region=southern)
WFO.objects.create(name="Melbourne", weight=0, code="MLB", region=southern)
WFO.objects.create(name="Shreveport", weight=0, code="SHV", region=southern)
WFO.objects.create(name="Lake Charles", weight=0, code="LCH", region=southern)
WFO.objects.create(name="Albuquerque", weight=0, code="ABQ", region=southern)
WFO.objects.create(name="Jackson", weight=0, code="JAN", region=southern)
WFO.objects.create(name="San Francisco", weight=8, code="MTR", region=western)
WFO.objects.create(name="Tucson", weight=2, code="TWC", region=western)
WFO.objects.create(name="Pendleton", weight=18, code="PDT", region=western)
WFO.objects.create(name="Pocatello", weight=0, code="PIH", region=western)
WFO.objects.create(name="Medford", weight=17, code="MFR", region=western)
WFO.objects.create(name="Los Angeles/Oxnard", weight=5, code="LOX", region=western)
WFO.objects.create(name="Phoenix", weight=1, code="PSR", region=western)
WFO.objects.create(name="Great Falls", weight=12, code="TFX", region=western)
WFO.objects.create(name="San Diego", weight=7, code="SGX", region=western)
WFO.objects.create(name="Spokane", weight=22, code="OTX", region=western)
WFO.objects.create(name="Las Vegas", weight=15, code="VEF", region=western)
WFO.objects.create(name="Glasgow", weight=11, code="GGW", region=western)
WFO.objects.create(name="Salt Lake City", weight=20, code="SLC", region=western)
WFO.objects.create(name="Missoula", weight=13, code="MSO", region=western)
WFO.objects.create(name="Billings", weight=10, code="BYZ", region=western)
WFO.objects.create(name="Boise", weight=9, code="BOI", region=western)
WFO.objects.create(name="Eureka", weight=3, code="EKA", region=western)
WFO.objects.create(name="Reno", weight=16, code="REV", region=western)
WFO.objects.create(name="Flagstaff", weight=0, code="FGZ", region=western)
WFO.objects.create(name="Sacramento", weight=6, code="STO", region=western)
WFO.objects.create(name="Hanford", weight=4, code="HNX", region=western)
WFO.objects.create(name="Elko", weight=14, code="LKN", region=western)
WFO.objects.create(name="Seattle", weight=21, code="SEW", region=western)
WFO.objects.create(name="Portland", weight=19, code="PQR", region=western)
WFO.objects.create(name="Juneau", weight=2, code="AJK", region=alaska)
WFO.objects.create(name="Fairbanks", weight=1, code="AFG", region=alaska)
WFO.objects.create(name="Anchorage", weight=0, code="AFC", region=alaska)

print("Done.")
