FROM ubuntu:24.04 AS geo-base

FROM geo-base AS builder

RUN apt-get update && \
    apt-get install software-properties-common -y

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://go.dev/dl/go1.26.5.linux-amd64.tar.gz -o golang.tar.gz && \
    tar -C /usr/local -xzf golang.tar.gz && \
    rm golang.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /tasks
COPY . .

RUN CGO_ENABLED=0 go build -o ghwo cmd/ghwo/main.go

FROM ubuntu:24.04 AS runtime

RUN rm -rf /var/lib/apt/lists/*

COPY --from=builder --chown=1001:1001 tasks/ghwo /usr/local/bin/ghwo

USER 1001

ENV PATH=$PATH:/usr/local/bin/ghwo

CMD ["ghwo"]
