"""
Django settings for weathergov project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import environs
from csp.constants import NONCE, SELF
from django.contrib.staticfiles.storage import ManifestStaticFilesStorage

SETTINGS_TYPE = "base"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[3]

env = environs.Env()

# Set the DEBUG setting based on the DJANGO_DEBUG env
# variable value
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=False)
TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ
API_TIMINGS_METADATA = env.bool("API_TIMINGS_METADATA", default=False)

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SAMESITE = 'None'
# SESSION_COOKIE_SAMESITE = 'None'
CSRF_TRUSTED_ORIGINS = [
    "https://sso.noaa.gov",
]

ALLOWED_HOSTS = [
    "weathergov-test.app.cloud.gov",
    "weathergov-staging.app.cloud.gov",
    "beta.weather.gov",
]

ALLOWED_CIDR_NETS = ["10.0.0.0/8"]

# For request paths without a trailing slash, add one automatically to resolve
# the handler. This is True by default, but let's set it explicitly to be...
# explicit.
APPEND_SLASH = True

# Application definition

OUR_APPS = [
    "backend",
    "spatial",
    "noaa_saml",
]

INSTALLED_APPS = [
    *OUR_APPS,
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.sitemaps",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "csp",
    # Wagtail dependencies
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "storages",
]

MIDDLEWARE = [
    # django-allow-cidr: enable use of CIDR IP ranges in ALLOWED_HOSTS
    "allow_cidr.middleware.AllowCIDRMiddleware",
    # serve static assets in production
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "csp.middleware.CSPMiddleware",
    # Wagtail related middleware
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    # Custom middleware for catching interop errors
    "backend.middleware.TooManyRequestsMiddleware",
    "backend.middleware.GatewayTimeoutMiddleware",
]

ROOT_URLCONF = "backend.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "backend.context_processors.route_info",
                "backend.context_processors.git_info",
            ],
            "builtins": [
                "django.templatetags.i18n",
                "django.templatetags.static",
                "backend.templatetags.weather_i18n",
                "backend.templatetags.weather_partials",
                "backend.templatetags.util",
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "noaa_saml.auth.NOAABackend",
]


AUTH_USER_MODEL = "backend.NOAAUser"

WSGI_APPLICATION = "backend.config.wsgi.application"

# any upload that exceeds this limit will raise a `SuspiciousOperation(RequestDataTooBig)`
DATA_UPLOAD_MAX_MEMORY_SIZE = 3 * 1024 * 1024  # 3MB


class CustomManifestStaticFilesStorage(ManifestStaticFilesStorage):
    """Override manifest storage to support ESM module imports."""

    support_js_module_import_aggregation = True


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "backend.config.settings.base.CustomManifestStaticFilesStorage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
# LANGUAGES = (
#     ("en", _(u"English")),
#     ("es", _(u"Spanish")),
#     ("zh-hans", _(u"Chinese"))
# )

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# URL to use when referring to static files located in STATIC_ROOT
# Must be relative and end with "/"
STATIC_URL = "public/"

STATIC_ROOT = BASE_DIR / "frontend" / "public"

STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "assets",
]


def get_base_pool_limits():
    """
    Get base pool limits.

    Ensure the databse pool allocation is spread evenly across
    all web instances, taking into accounty gevent workers
    """
    max_connections = int(os.environ.get("WEB_DB_MAX_CONNECTIONS", "45"))
    instances = int(os.environ.get("WEB_INSTANCES", "1")) * int(os.environ.get("WEB_GEVENT_WORKERS", "1"))
    max_size = max(max_connections // instances, 10)
    min_size = max(max_size // 2, 5)
    return {"min_size": min_size, "max_size": max_size}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": "database",
        "PORT": 5432,
        "OPTIONS": {"pool": get_base_pool_limits()},
    },
}


# Wagtail related settings
# See https://docs.wagtail.org/en/stable/getting_started/integrating_into_django.html
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

WAGTAIL_SITE_NAME = "beta.weather.gov"
WAGTAILADMIN_BASE_URL = "http://localhost:8080"  # Change to env variable for config
WAGTAILDOCS_EXTENSIONS = ["jpg", "jpeg", "pdf", "png", "gif"]
WAGTAILDOCS_SERVE_METHOD = "redirect"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# i18n
LOCALE_PATHS = [BASE_DIR / "locale"]

# Custom site information
SITE_LOGO = "logo.svg"
SITE_NAME = "beta.weather.gov"
SITE_SLOGAN = "National Weather Service"
AGENCY_NAME = "National Weather Service"

# 3rd party sites that weather.gov needs to access in order to function
# don't put tracking or analytics domains in this list, please
#               (you will break the site for some people if you do)
# HOSTS ONLY (domain + port)! No schema or wildcards, please
CRITICAL_HOSTS = {
    "connect-src": [
        # cmi-radar
        "api.weather.gov",
        # mapping
        "static.arcgis.com",
        "geocode.arcgis.com",
        "basemapstyles-api.arcgis.com",
        "basemaps-api.arcgis.com",
        "cdn.arcgis.com",
        "opengeo.ncep.noaa.gov",
        # satellite
        "cdn.star.nesdis.noaa.gov",
    ],
    "img-src": [
        # satellite
        "cdn.star.nesdis.noaa.gov",
        # mapping
        "opengeo.ncep.noaa.gov",
        "cdn.arcgis.com",
        # legacy weather.gov images
        "www.weather.gov",
        # weather stories
        "api.weather.gov",
    ],
    "media-src": [
        # satellite
        "cdn.star.nesdis.noaa.gov",
    ],
}

if any("*" in site for group in CRITICAL_HOSTS.values() for site in group):
    raise TypeError("Please don't use wildcards in CRITICAL_HOSTS")  # noqa: TRY003

# content security policy configuration
DIRECTIVES = {
    "default-src": [SELF],
    "script-src": [
        SELF,
        # required for cmi-radar
        "'unsafe-eval'",
        # Required for Wagtail
        "'unsafe-inline'",
    ],
    "script-src-elem": [
        SELF,
        # required for CDN hosted javascript
        NONCE,
        # analytics
        "dap.digitalgov.gov",
        "www.googletagmanager.com",
        "client.rum.us-east-1.amazonaws.com",
        # Required for Wagtail
        "'unsafe-inline'",
    ],
    "connect-src": [
        SELF,
        # analytics
        "www.google-analytics.com",
        "dap.digitalgov.gov",
        "cognito-identity.us-east-1.amazonaws.com",
        "dataplane.rum.us-east-1.amazonaws.com",
        *CRITICAL_HOSTS["connect-src"],
    ],
    "font-src": [SELF],
    "img-src": [
        SELF,
        # analytics
        "www.google-analytics.com",
        "www.googletagmanager.com",
        # gravatar (only on wagtail)
        "www.gravatar.com",
        *CRITICAL_HOSTS["img-src"],
        # esri-leaflet-vector.js
        "data:",
    ],
    "media-src": [SELF, *CRITICAL_HOSTS["media-src"]],
    "worker-src": [
        SELF,
        # alertMap.js
        "blob:",
    ],
    "frame-ancestors": [SELF],
    "form-action": [SELF],
}

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        **DIRECTIVES,
        "style-src": [
            SELF,
            "'unsafe-inline'",
        ],
    },
}

CONTENT_SECURITY_POLICY_REPORT_ONLY = {
    "DIRECTIVES": {
        **DIRECTIVES,
        # report style-src violations
        "style-src": [
            SELF,
            NONCE,
            # cmi-radar
            "'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='",
            "'sha256-624gmqlO23N0g1Ru4tkjuaPEoL/hXP4w7tUqel4WM98='",
            "'sha256-5uOIRR03mYcVoiexgzGGALQ0p1Babe2XxbeIl9t1UpA='",
            "'sha256-lM8P08IzH0mbT5Tvlm1F5BY3h0gPsb0qNpnZW9YHc7A='",
            # esri-leaflet
            "'sha256-UykT9B84Ik0dt1VPV3lpHxAikh/bNzWCgLl3XN0PYtw='",
            "'sha256-RXxNUJG3UfHAeHA4copS/oAu4QHoWavn3IraEQ+XrTk='",
            "'sha256-PhvAqgz4qsgszcJzzo3ctihcuOyVv4VbFiW+ns+wtJM='",
        ],
    },
}

# region: Logging-----------------------------------------------------------###

# A Python logging configuration consists of four parts:
#   Loggers
#   Handlers
#   Filters
#   Formatters
# https://docs.djangoproject.com/en/4.1/topics/logging/

# Log a message by doing this:
#
#   import logging
#   logger = logging.getLogger(__name__)
#
# Then:
#
#   logger.debug("We're about to execute function xyz. Wish us luck!")
#   logger.info("Oh! Here's something you might want to know.")
#   logger.warning("Something kinda bad happened.")
#   logger.error("Can't do this important task. Something is very wrong.")
#   logger.critical("Going to crash now.")


LOGGING = {
    "version": 1,
    # Don't import Django's existing loggers
    "disable_existing_loggers": False,
    # define how to convert log messages into text;
    # each handler has its choice of format
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%d/%b/%Y %H:%M:%S",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
    },
    # define where log messages will be sent
    # each logger can have one or more handlers
    "handlers": {
        "console": {
            "level": os.environ.get("DJANGO_LOG_LEVEL", "DEBUG"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        # No file logger is configured,
        # because containerized apps
        # do not log to the file system.
    },
    # define loggers: these are "sinks" into which
    # messages are sent for processing
    "loggers": {
        # Django's generic logger
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's template processor
        "django.template": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's runserver
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's requests
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        **{
            app: {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            }
            for app in OUR_APPS
        },
    },
    # root logger catches anything, unless
    # defined by a more specific logger
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# endregion

# SAML
SAML_CREATES_NEW_USERS = True
SAML_LOCAL_DEV = False


if DEBUG:
    # used by debug() context processor
    INTERNAL_IPS = [
        "127.0.0.1",
        "::1",
    ]

# choose whether or not to show menu links that do not go anywhere. this is
# enabled for default in local environments and disabled for production.
DEBUG_SHOW_ALL_MENU_LINKS = False
