---
default_config: &defaults
  buildpacks:
    # We need the "apt" buildpack to install a MySQL client for Drush; see apt.yml
    - https://github.com/cloudfoundry/apt-buildpack.git
    - php_buildpack
  disk_quota: 2G
  timeout: 180
  env:
    PHP_INI_SCAN_DIR: /home/vcap/app/php/etc/:/home/vcap/app/php/etc/php.ini.d/
    NEWRELIC_LICENSE: ((newrelic-license))
  services:
    - database
    - storage
    - secrets

applications:
  - name: weathergov-eric
    <<: *defaults
    memory: 256M
    instances: 1
    random-route: false

  - name: api-weathergov-eric
    stack: cflinuxfs4
    memory: 256M
    instances: 1
    buildpacks:
      - nodejs_buildpack
    env:
      NEWRELIC_LICENSE: ((newrelic-license))
      API_INTEROP_PRODUCTION: true
      API_INTEROP_NAME: eric
    health-check-type: process
    path: ../api-interop-layer
    random-route: false
    services:
      - database
# - name: cronish
#   <<: *defaults
#   no-route: true
#   command: ./cronish.sh
#   health-check-type: process
#   memory: 128M
