# Generated by Django 6.0.5 on 2026-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration): # noqa: D101

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="RiskData",
            fields=[
                ("id", models.CharField(max_length=5, primary_key=True, serialize=False)),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "weathergov_risk_data",
            },
        ),
        migrations.CreateModel(
            name="RiskErrors",
            fields=[
                ("id", models.CharField(max_length=3, primary_key=True, serialize=False)),
                ("is_error", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "weathergov_risk_wfo_errors",
            },
        ),
    ]
