@startuml weather.gov software stack
!include  <C4/C4_Component.puml>

LAYOUT_WITH_LEGEND()
title weather.gov software stack
skinparam linetype polyline


Person_Ext(anon, "Public user")

System_Boundary(web, "legacy weather.gov") {
  System(django, "Django")
  ComponentDb(db, "PostGIS")
  Component(data, "API interop layer")
}

System_Ext(proxy, "proxy/bundler")
ComponentDb(proxydata, "proxy data")

System_Ext(api, "api.weather.gov")
System_Ext(legacy, "weather.gov")

BiRel(django, db, "Stores content and spatial data")
Rel(django, data, "Gets weather data")

Rel(anon, django, "visits the site")

BiRel(proxy, proxydata, "Serves saved\nforecast data\n\nSaves forecast\ndata for replay")

Rel(proxy, api, "Fetches data from api.weather.gov")
Rel(data, proxy, "Fetches data from proxy")
Rel(data, legacy, "Fetches satellite data")
Rel(proxy, legacy, "Fetches GHWO data")

@enduml
