@startuml weather.gov software stack

# Make this more about user flows than actual software stack. User comes in via
# browser, hits Apache, gets handed off to Drupal, uses modules, etc. to figure
# out what to render, pulls data from the database, assembles it all back
# together, and pushes it back out to the browser.

package "CMS" {
  [USWDS theme] as m1
  [Weather blocks module] as m2
  [Weather data module] as m3
  [Drupal]
  [MySQL]
}

m1 --> Drupal
m2 --> Drupal
m3 --> Drupal

[Apache]
Drupal <--> Apache

Drupal <--> MySQL

@enduml