runs:
  using: composite
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: install dependencies
      shell: bash
      run: npm ci

    - name: install proxy dependencies
      shell: bash
      run: cd tests/api && npm ci

    - name: install api-interop-layer dependencies
      shell: bash
      run: cd api-interop-layer && npm ci

    - name: add problem matcher
      shell: bash
      run: echo "::add-matcher::${{ github.workspace }}/.github/workflows/problem-matcher-eslint.json"

    - name: run eslint
      shell: bash
      run: npm run js-lint
