runs:
  using: composite
  steps:
    - name: prepare playwright
      uses: ./.github/actions/setup-playwright
    - name: run tests
      shell: bash
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} e2e/*
    - name: Upload blob report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: ${{ defaults.run.working-directory }}
        retention-days: 1
