FROM golang:1.23

WORKDIR /app

# Copy modules
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build
RUN go build -o server ./cmd/server

# Expose port
EXPOSE 8082

# Run (dev mode uses air or just run binary)
CMD ["./server"]