# Generated by Django 5.1.6 on 2025-02-21 18:06

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicSafetyInformation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=256, unique=True)),
                ("label", models.CharField(max_length=256)),
                ("body", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="wfo",
            name="region",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="region",
                to="backend.region",
            ),
        ),
    ]
