# Generated by Django 5.2.6 on 2025-09-05 21:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_dynamicsafetyinformation_alter_wfo_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wfo",
            name="region",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="wfos", to="backend.region",
            ),
        ),
    ]
