# Generated by Django 5.2.6 on 2025-09-09 19:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_wfo_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="wfo",
            name="about",
            field=wagtail.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="wfo",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="wfo",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="wfo",
            name="facebook",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="wfo",
            name="phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="wfo",
            name="twitter",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="wfo",
            name="youtube",
            field=models.URLField(blank=True),
        ),
    ]
