# Generated by Django 5.2.6 on 2025-09-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    def delete_initial_dynamic_safety_info_data(apps, schema_editor):
        DynamicSafetyInformation = apps.get_model('backend', 'DynamicSafetyInformation')

        DynamicSafetyInformation.objects.all().delete()

    def load_initial_dynamic_safety_info_data(apps, schema_editor):
        DynamicSafetyInformation = apps.get_model('backend', 'DynamicSafetyInformation')

        # clear out any pre-existing DynamicSafetyInformation instances.
        DynamicSafetyInformation.objects.all().delete()

        DynamicSafetyInformation.objects.create(
            type="excessive heat warning",
            label="Excessive Heat Warning",
            body="<p dir=\"ltr\">An Excessive Heat Warning means that extremely dangerous heat conditions are happening now or soon. You must take precautions to protect yourself and others from extreme heat.&nbsp;</p><ul><li dir=\"ltr\">Stay inside in air conditioning if possible. If you don’t have air conditioning, go to a library, mall, or local cooling center.&nbsp;</li><li dir=\"ltr\">Drink plenty of water to stay hydrated, and wear loose, light-colored clothing.&nbsp;</li><li dir=\"ltr\">Check on friends, family, and neighbors, especially those who do not have air conditioning or spend much of their time alone.&nbsp;</li><li dir=\"ltr\">Reschedule outdoor activities for a cooler day.</li><li dir=\"ltr\">If you must be outdoors, take longer and more frequent breaks in the shade or air conditioning, and avoid the hottest parts of the day.</li><li dir=\"ltr\">Bring pets indoors if possible. If pets are left outside, make sure they have shade and plenty of cool water.&nbsp;</li><li dir=\"ltr\">Make sure you know the&nbsp;<a href=\"https://www.ready.gov/heat#illness\">signs of heat-related illness</a> and how to respond.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="air stagnation advisory",
            label="Air stagnation advisory",
            body="<p dir=\"ltr\">An Air Stagnation Advisory means that conditions are causing or may lead to air pollution build up in some areas.&nbsp;</p><ul><li dir=\"ltr\">Check the air quality levels in your area at&nbsp;<a href=\"https://www.airnow.gov/\">airnow.gov</a>.&nbsp;</li><li dir=\"ltr\">Limit your time outdoors, especially if you have respiratory problems or other health concerns. This includes seniors, children, or those with asthma or other health conditions.&nbsp;</li><li dir=\"ltr\">If you are at higher risk of respiratory illness and must spend time outdoors, consider wearing an N95 mask.</li><li dir=\"ltr\">Reduce time spent running vehicles, generators, or other activities that can add to local air pollution.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="extreme cold warning",
            label="Extreme Cold Warning",
            body="<p dir=\"ltr\">An Extreme Cold Warning means that dangerously cold temperatures or wind chills are happening now or soon. Take immediate action to protect yourself, your home and your loved ones.&nbsp;</p><ul><li dir=\"ltr\">Stay indoors as much as possible.</li><li dir=\"ltr\">If you must go outside, dress in warm layers and cover every part of your body, including ears, nose, toes and fingers.&nbsp;</li><li dir=\"ltr\">Make sure pets and livestock have access to food, water, and shelter from the cold.&nbsp;</li><li dir=\"ltr\">Have at least half a tank of gas in your car before driving longer distances so that you can stay warm if you become stranded.&nbsp;</li><li dir=\"ltr\">If using heat from a fireplace or wood stove, make sure to ventilate properly. Never use a gas range or oven to heat your home. If using a generator, it should be placed outdoors, at a distance from the home.&nbsp;</li><li dir=\"ltr\">Check on older friends, family and neighbors to ensure they’re staying warm. &nbsp;&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="flood warning",
            label="Flood warning",
            body="<p dir=\"ltr\">A Flood Warning means that dangerous flooding is expected or already happening. Take immediate action to protect yourself and your home.&nbsp;</p><ul><li dir=\"ltr\">If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li><li dir=\"ltr\">If you are trapped in a building, move to the highest floor and call 911. Go to the roof only if necessary.&nbsp;</li><li dir=\"ltr\">Do not go into any room where electrical cords or outlets are under water. Stay out of water that may have electricity in it!</li><li dir=\"ltr\">If your vehicle is trapped in rapidly moving water, stay inside. If water is rising inside the vehicle, move to the roof and signal for help.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="ashfall advisory",
            label="Ashfall advisory",
            body="<p dir=\"ltr\">An Ashfall Advisory means that minor ashfall (less than one-quarter inch) is happening now or soon.&nbsp;</p><ul><li dir=\"ltr\">Unless local officials are telling you to evacuate, stay indoors, and seal all doors and windows in the building.&nbsp;</li><li dir=\"ltr\">Bring pets inside, and lead livestock under shelter.</li><li dir=\"ltr\">Cover all air intakes and open water supplies.&nbsp;</li><li dir=\"ltr\">Avoid driving, especially if visibility is low.&nbsp;</li><li dir=\"ltr\">If you must go outside, wear a mask to avoid inhaling ash, and safety glasses or goggles to protect your eyes.&nbsp;</li><li dir=\"ltr\">Monitor news and weather alerts to get updates on the situation.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="flash flood warning",
            label="Flash flood warning",
            body="<p dir=\"ltr\">A Flash Flood Warning means that dangerous flooding is expected or already happening. Flash flooding can develop in hours or minutes, so take protective action now.&nbsp;&nbsp;</p><ul><li dir=\"ltr\">If you are in a low-lying or flood prone area, move to higher ground&nbsp;<em><strong>immediately</strong></em>.&nbsp;&nbsp;</li><li dir=\"ltr\">Stay off bridges over fast-moving water, and away from storm drains, culverts, creeks and streams.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">If you are trapped in a building, move to the highest floor and call 911. Go to the roof only if necessary.&nbsp;</li><li dir=\"ltr\">If your vehicle is trapped in rapidly moving water, stay inside. If water is rising inside the vehicle, move to the roof and signal for help.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="wind chill watch",
            label="Wind Chill Watch",
            body="<p dir=\"ltr\">A Wind Chill Watch means that winds are likely to be dangerously cold, and you should take action to protect yourself and your loved ones from frostbite.&nbsp;</p><ul><li dir=\"ltr\">Stay indoors as much as possible.</li><li dir=\"ltr\">If you must go outside, dress in warm layers and cover every part of your body, including ears, nose, toes and fingers. Stay out of the wind as much as possible.&nbsp;</li><li dir=\"ltr\">Keep pets indoors, and lead livestock to shelter.&nbsp;</li><li dir=\"ltr\">When safe, check on older friends, family and neighbors to ensure they’re staying warm. &nbsp;&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="lakeshore flood watch",
            label="Lakeshore flood watch",
            body="<p dir=\"ltr\">A Flood Watch means the area may experience a dangerous flooding event, and being prepared may save lives and property.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check your home’s&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies</a>, and make sure all members of the household know your&nbsp;<a href=\"https://www.ready.gov/plan\">emergency plan</a>.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul><p dir=\"ltr\">If a Flood Warning is issued, it means that dangerous flooding is expected or already happening.&nbsp;</p><ul><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li></ul><p>If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="high wind watch",
            label="High Wind Watch",
            body="<p dir=\"ltr\">A High Wind Watch means that strong, potentially dangerous winds are expected, and you should be prepared to protect yourself and your property.&nbsp;</p><ul><li dir=\"ltr\">Stay indoors if possible. Especially avoid being outside in forested areas or around large trees.&nbsp;</li><li dir=\"ltr\">Secure trash cans, lawn furniture, and outdoor objects that the wind may be able to pick up.</li><li dir=\"ltr\">Charge cell phones and other essential devices, and check that you have flashlights and batteries in case of a power outage.&nbsp;</li><li dir=\"ltr\">Be alert and use extra caution when driving, especially if operating a high profile vehicle like a van, truck or SUV.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="freeze watch",
            label="Freeze Watch",
            body="<p dir=\"ltr\">A Freeze Watch means that temperatures will be low enough to lead to freezing in some areas.&nbsp;</p><ul><li dir=\"ltr\">Bring young or vulnerable plants indoors to protect them from the cold</li><li dir=\"ltr\">Wrap or drain outdoor pipes to prevent them from freezing</li><li dir=\"ltr\">Drain in-ground sprinkler systems&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="winter weather advisory",
            label="Winter Weather Advisory",
            body="<p dir=\"ltr\">A Winter Weather Advisory means that your area can expect or is seeing some amount of snow, ice, or sleet. Weather conditions may be inconvenient or even dangerous.&nbsp;</p><ul><li dir=\"ltr\">Plan for any travel to take extra time.&nbsp;&nbsp;</li><li dir=\"ltr\">Slow down and use caution while driving.&nbsp;</li><li dir=\"ltr\">Stay tuned for updates here or through local radio and news.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="dense fog advisory",
            label="Dense fog advisory",
            body="<p dir=\"ltr\">A Dense Fog Advisory means that thick fog is happening now or very soon. It will limit visibility to less than a quarter mile, creating dangerous travel conditions.&nbsp;</p><ul><li dir=\"ltr\">Limit driving or other travel if possible.&nbsp;</li><li dir=\"ltr\">If driving, slow down and plan for extra travel time to reach your destination.&nbsp;</li><li dir=\"ltr\">Use headlights and fog lights if you have them. Do not use high-beam lights, as the glare makes it more difficult for you to see.&nbsp;</li><li dir=\"ltr\">Leave plenty of distance between you and other vehicles.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="dust storm warning",
            label="Dust storm warning",
            body="<p dir=\"ltr\">A Dust Storm Warning means that blowing dust, strong winds and dangerously low visibility are happening now or very soon.&nbsp;&nbsp;</p><ul><li dir=\"ltr\">Go indoors immediately. Close all doors and windows, and turn off the AC to keep dust outside.&nbsp;</li><li dir=\"ltr\">If you are driving, find a safe place to pull off and away from the road. Turn your lights off, and set the emergency brake.&nbsp;<em><strong>Never</strong></em> stop on the roadway itself.&nbsp;</li><li dir=\"ltr\">If you cannot safely pull off the road, slow down, turn on your lights, and honk your horn occasionally to let other drivers know you are there. Proceed slowly, using the center line as a guide, until you find a safe place to pull off the road.&nbsp;&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="ashfall warning",
            label="Ashfall warning",
            body="<p dir=\"ltr\">An Ashfall Warning means that the area is seeing heavy ashfall, and you should take immediate action.&nbsp;&nbsp;</p><ul><li dir=\"ltr\">If officials direct you to evacuate,&nbsp;<em><strong>do so immediately</strong></em>. Otherwise, stay indoors and seal all doors and windows in the building. Stay there until authorities say it is safe to go outside.&nbsp;</li><li dir=\"ltr\">Bring pets inside and lead livestock under shelter.</li><li dir=\"ltr\">Place damp towels along door jambs or other areas where ash may be able to get in.</li><li dir=\"ltr\">Cover all air intakes and open water supplies.&nbsp;</li><li dir=\"ltr\">Avoid driving, especially if visibility is low.&nbsp;</li><li dir=\"ltr\">If you must go outside, wear a mask to avoid inhaling ash, and safety glasses or goggles to protect your eyes.&nbsp;</li><li dir=\"ltr\">Stay tuned to local news for the latest updates, and follow all instructions from local officials.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="flash flood watch",
            label="Flash flood watch",
            body="<p dir=\"ltr\">A Flood Watch means the area may experience a dangerous flooding event, and being prepared may save lives and property.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check your home’s&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies</a>, and make sure all members of the household know your&nbsp;<a href=\"https://www.ready.gov/plan\">emergency plan</a>.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul><p dir=\"ltr\">If a Flood Warning is issued, it means that dangerous flooding is expected or already happening.&nbsp;</p><ul><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li></ul><p>If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="air quality alert",
            label="Air quality alert",
            body="<p dir=\"ltr\">When an Air Quality Alert is active for your location:&nbsp;</p><ul><li dir=\"ltr\">Check the air quality levels in your area at&nbsp;<a href=\"https://www.airnow.gov/\">airnow.gov</a>.&nbsp;</li><li dir=\"ltr\">Limit your time outdoors, especially if you are at higher risk. This includes seniors, children, or those with asthma or other health conditions.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="coastal flood advisory",
            label="Coastal flood advisory",
            body="<p dir=\"ltr\">A Flood Advisory is issued when flooding may cause significant inconvenience, or even become dangerous if you are not careful. Know your risk at home, work and school, and use caution when flooding is expected.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check road conditions before traveling, and obey road closures and barricades.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="high surf advisory",
            label="High Surf Advisory",
            body="<p dir=\"ltr\">A High Surf Advisory means that breaking waves could result in dangerous conditions.&nbsp;</p><ul><li>Very strong waves could be dangerous to anyone in the water and along the shore.&nbsp;</li><li>Always stay near lifeguards.</li><li>Stay off of rocks or jetties where large waves could pop up suddenly.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="flood watch",
            label="Flood watch",
            body="<p dir=\"ltr\">A Flood Watch means the area may experience a dangerous flooding event, and being prepared may save lives and property.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check your home’s&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies</a>, and make sure all members of the household know your&nbsp;<a href=\"https://www.ready.gov/plan\">emergency plan</a>.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul><p dir=\"ltr\">If a Flood Warning is issued, it means that dangerous flooding is expected or already happening.&nbsp;</p><ul><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li></ul><p>If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="extreme cold watch",
            label="Extreme Cold Watch",
            body="<p dir=\"ltr\">An Extreme Cold Watch means that it may become dangerously cold, and you should take action to protect yourself and your loved ones.&nbsp;</p><ul><li dir=\"ltr\">Stay indoors as much as possible.</li><li dir=\"ltr\">If you must go outside, dress in warm layers and cover every part of your body, including ears, nose, toes and fingers.&nbsp;</li><li dir=\"ltr\">Make sure pets and livestock have access to food, water, and shelter from the cold.&nbsp;</li><li dir=\"ltr\">Check in on neighbors, family, and friends, ensuring they have a plan to keep warm.&nbsp;&nbsp;&nbsp;</li><li dir=\"ltr\">Have at least half a tank of gas in your car before driving longer distances so that you can stay warm if you become stranded.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="coastal flood watch",
            label="Coastal flood watch",
            body="<p dir=\"ltr\">A Flood Watch means the area may experience a dangerous flooding event, and being prepared may save lives and property.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check your home’s&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies</a>, and make sure all members of the household know your&nbsp;<a href=\"https://www.ready.gov/plan\">emergency plan</a>.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul><p dir=\"ltr\">If a Flood Warning is issued, it means that dangerous flooding is expected or already happening.&nbsp;</p><ul><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li></ul><p>If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="excessive heat watch",
            label="Excessive Heat Watch",
            body="<p dir=\"ltr\">An Excessive Heat Watch means to expect extremely dangerous heat conditions in the next few days. Take action ahead of time to stay safe during extreme heat.</p><ul><li dir=\"ltr\">Plan to stay in air-conditioned spaces if possible. Find cooling centers or places with AC in your community that you can go to, like libraries or shopping malls.&nbsp;</li><li dir=\"ltr\">Cover windows with curtains or shades, or use window reflectors designed to reflect heat back outside.&nbsp;</li><li dir=\"ltr\">Make sure you know the&nbsp;<a href=\"https://www.ready.gov/heat#illness\">signs of heat-related illness</a> and how to respond.</li><li dir=\"ltr\">Stock up on clean drinking water.&nbsp;</li><li dir=\"ltr\">Check in on neighbors, family, and friends, ensuring they have a plan to keep cool.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="freeze warning",
            label="Freeze Warning",
            body="<p dir=\"ltr\">A Freeze Warning means that temperatures will drop below freezing in your area.&nbsp;</p><ul><li dir=\"ltr\">Bring young or vulnerable plants indoors to protect them from the cold</li><li dir=\"ltr\">Wrap or drain outdoor pipes to prevent them from freezing</li><li dir=\"ltr\">Drain in-ground sprinkler systems&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="frost advisory",
            label="Frost Advisory",
            body="<p>A Frost Advisory means that your area is likely to see frost developing overnight, which can harm young or vulnerable plants. Cover these plants before the sun goes down to help them retain heat.&nbsp;</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="tsunami watch",
            label="Tsunami watch",
            body="<p dir=\"ltr\">A Tsunami Watch means there has been a distant earthquake that may have created a tsunami that could impact the area. Scientists at the <a href=\"https://www.tsunami.gov/\">National Tsunami Warning Center</a> are working to evaluate the threat and will have more information soon.</p><ul><li dir=\"ltr\">Stay tuned for more information. Monitor local news, television or weather alerts for emergency updates.&nbsp;</li><li dir=\"ltr\">Follow all instructions from local officials.&nbsp;</li><li dir=\"ltr\">Check if you are in a tsunami hazard zone. If so, look up local evacuation routes and be ready to leave if necessary.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="coastal flood warning",
            label="Coastal flood warning",
            body="<p dir=\"ltr\">A Flood Warning means that dangerous flooding is expected or already happening. Take immediate action to protect yourself and your home.&nbsp;</p><ul><li dir=\"ltr\">If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li><li dir=\"ltr\">If you are trapped in a building, move to the highest floor and call 911. Go to the roof only if necessary.&nbsp;</li><li dir=\"ltr\">Do not go into any room where electrical cords or outlets are under water. Stay out of water that may have electricity in it!</li><li dir=\"ltr\">If your vehicle is trapped in rapidly moving water, stay inside. If water is rising inside the vehicle, move to the roof and signal for help.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="lakeshore flood advisory",
            label="Lakeshore flood advisory",
            body="<p dir=\"ltr\">A Lakeshore Flood Advisory is issued when flooding may cause significant inconvenience, or even become dangerous if you are not careful. Know your risk at home, work and school, and use caution when flooding is expected.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check road conditions before traveling, and obey road closures and barricades.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters.&nbsp;</li><li dir=\"ltr\">If you live on or near the shore, take action to protect your property from rising water. Move outdoor items, bring pets indoors, and place sandbags if needed.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="blizzard warning",
            label="Blizzard Warning",
            body="<p dir=\"ltr\">A Blizzard Warning means that your area is seeing or expecting strong winds and heavy or blowing snow. This can cause low visibility and very dangerous conditions.&nbsp;</p><ul><li dir=\"ltr\">Do not travel unless an emergency requires it. If you must travel, make sure you have an&nbsp;<a href=\"https://www.ready.gov/car\">emergency kit in your car</a> and a full tank of gas and/or a fully charged battery.&nbsp;</li><li dir=\"ltr\">If you get stuck in your vehicle, stay there and contact the authorities for help. Run the motor for 10 minutes per hour for heat, but open the windows just a little for fresh air.&nbsp;</li><li dir=\"ltr\">At home, stay indoors until the storm has passed.&nbsp;</li><li dir=\"ltr\">Make sure that pets and other animals have plenty of food and water, and access to a warm shelter.</li><li dir=\"ltr\">If using heat from a fireplace or wood stove, make sure to ventilate properly. Never use a gas range or oven to heat your home. If using a generator, it should be placed outdoors, at a distance from the home.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="winter storm watch",
            label="Winter Storm Watch",
            body="<p dir=\"ltr\">A Winter Storm Watch means that the area could see a significant winter storm, including sleet, heavy snow, ice, or some combination. Take action now to prepare your home, vehicle and family.&nbsp;</p><ul><li dir=\"ltr\">Make sure you have an&nbsp;<a href=\"https://www.ready.gov/car\">emergency kit in your car</a>, and&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies in your home</a>. These should include food, water, essential medications, and spare phone chargers.&nbsp;&nbsp;</li><li dir=\"ltr\">Try to avoid travel when winter weather is expected. If you must drive in the snow, make sure you have a full tank of gas and/or a fully charged battery. Go slowly and keep your distance from other vehicles.&nbsp;</li><li dir=\"ltr\">Make sure that pets and other animals have plenty of food and water, and access to a warm shelter.</li><li dir=\"ltr\">Stay tuned for updates here or through local radio and news.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="blowing dust advisory",
            label="Blowing dust advisory",
            body="<p dir=\"ltr\">A Blowing Dust Advisory means that your area may see blowing dust, and you should prepare for lower visibility.&nbsp;</p><ul><li dir=\"ltr\">If blowing dust comes to your area, go indoors. Until it has passed, close all doors and windows, and turn off the AC to keep dust outside.&nbsp;</li><li dir=\"ltr\">If you are driving, find a safe place to pull off and away from the road. Turn your lights off so as to not confuse other drivers when visibility is low.&nbsp;<em><strong>Never</strong></em> stop on the roadway itself.&nbsp;</li><li dir=\"ltr\">If you cannot safely pull off the road, slow down, turn on your lights, and honk your horn occasionally to let other drivers know you are there. Proceed slowly, using the center line as a guide, until you find a safe place to pull off the road.&nbsp;&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="tsunami warning",
            label="Tsunami warning",
            body="<p dir=\"ltr\">A Tsunami Warning means a tsunami has been confirmed, and may cause sudden and dangerous flooding and powerful currents along the coast. Tsunami waves could last for several hours or days, and the first wave may not be the largest</p><ul><li dir=\"ltr\">Leave coastal areas in the tsunami hazard zone&nbsp; <em><strong>immediately</strong></em>, and move inland to higher ground.&nbsp;</li><li dir=\"ltr\">Follow all instructions from local officials. If you have evacuated, stay in your safer location until officials tell you it is safe to return.&nbsp;</li><li dir=\"ltr\">Stay tuned for more information. Monitor local news, television or weather alerts.&nbsp;</li><li dir=\"ltr\">Limit non-emergency phone calls to keep the lines open for emergency communications.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="heat advisory",
            label="Heat Advisory",
            body="<p dir=\"ltr\">A Heat Advisory means dangerous heat conditions are happening now or soon. Take action before, during and after the heat to stay safe.&nbsp;</p><ul><li dir=\"ltr\">Stay in air-conditioned spaces if possible. Find cooling centers or places with AC in your community that you can go to, like libraries or shopping malls.&nbsp;</li><li dir=\"ltr\">Stay hydrated and stock up on clean drinking water to get you through multiple days of heat.</li><li dir=\"ltr\">Reschedule outdoor activities for cooler times of the day, and take breaks in the shade or air conditioning.</li><li dir=\"ltr\">Cover windows with curtains or shades, or use window reflectors designed to reflect heat back outside.&nbsp;</li><li dir=\"ltr\">Check on friends, family, and neighbors, especially those who do not have air conditioning or spend much of their time alone.&nbsp;</li></ul><p>Make sure you know the&nbsp;<a href=\"https://www.weather.gov/safety/heat-illness\">signs of heat-related illness</a> and how to respond.</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="ice storm warning",
            label="Ice Storm Warning",
            body="<p dir=\"ltr\">An Ice Storm Warning means that your area is expected to see enough ice to make travel dangerous, and possibly lead to downed power lines and falling tree branches.&nbsp;</p><ul><li dir=\"ltr\">Do not travel unless an emergency requires it. If you must travel, make sure you have an&nbsp;<a href=\"https://www.ready.gov/car\">emergency kit in your car</a> and a full tank of gas and/or a fully charged battery.&nbsp;</li><li dir=\"ltr\">If you get stuck in your vehicle, stay there and contact the authorities for help. Run the motor for 10 minutes per hour for heat, but open the windows just a little for fresh air.&nbsp;</li><li dir=\"ltr\">At home, prepare for a possible power outage. Check your&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies</a> for flashlights and batteries, and charge mobile devices.&nbsp;</li><li dir=\"ltr\">Make sure that pets and other animals have plenty of food and water, and access to a warm shelter.</li><li dir=\"ltr\">If using heat from a fireplace or wood stove, make sure it is properly ventilated. Never use a gas range or oven to heat your home. If using a generator, it should be placed outdoors, at a distance from the home.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="tsunami advisory",
            label="Tsunami advisory",
            body="<p dir=\"ltr\"><strong>You may see:</strong></p><ul><li dir=\"ltr\">Sudden and rapid changes in water levels along beaches, harbors, and waterways&nbsp;</li><li dir=\"ltr\">Dangerously strong and unusual currents</li><li dir=\"ltr\">Damage is possible to harbor infrastructure and boats and ships in port&nbsp;</li><li dir=\"ltr\">Some inundation is possible; tsunami impacts will be worse around high tide.</li></ul><p dir=\"ltr\"><strong>What to do:</strong>&nbsp;&nbsp;</p><ul><li dir=\"ltr\">Stay clear of beaches, harbors, and waterways</li><li dir=\"ltr\">Follow all instructions from local officials&nbsp;</li><li dir=\"ltr\">Check often for updated information</li><li dir=\"ltr\">Boaters far from land should head to the deepest water you can reach: 30 to 100 fathoms (180-300 feet) is best.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="winter storm warning",
            label="Winter Storm Warning",
            body="<p dir=\"ltr\">A Winter Storm Warning means that a dangerous winter storm is expected, making travel difficult or impossible. Take immediate action to prepare your home, vehicle and family.&nbsp;</p><ul><li dir=\"ltr\">Avoid travel if possible. If you must travel, check road conditions and closures before you leave, and make sure you have an&nbsp;<a href=\"https://www.ready.gov/car\">emergency kit in your car</a>.&nbsp; Make sure you have a full tank of gas and/or a fully charged battery.&nbsp;</li><li dir=\"ltr\">Stock&nbsp;<a href=\"https://www.ready.gov/kit\">emergency supplies in your home</a> before the storm hits. Include food, water, essential medications, flashlights and batteries.</li><li dir=\"ltr\">Make sure that pets and other animals have plenty of food and water, and access to a warm shelter.</li><li dir=\"ltr\">If using heat from a fireplace or wood stove, make sure it is properly ventilated. Never use a gas range or oven to heat your home. If using a generator, it should be placed outdoors, at a distance from the home.&nbsp;</li><li dir=\"ltr\">If stuck in your vehicle, stay there and contact the authorities for help. Run the motor about 10 minutes per hour for heat, but open the windows just a little for fresh air.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="lakeshore flood warning",
            label="Lakeshore flood warning",
            body="<p dir=\"ltr\">A Flood Warning means that dangerous flooding is expected or already happening. Take immediate action to protect yourself and your home.&nbsp;</p><ul><li dir=\"ltr\">If your home is likely to flood, or if authorities tell you to evacuate, do so&nbsp;<em><strong>immediately</strong></em> and move to higher ground.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters or flooded roads.&nbsp;</li><li dir=\"ltr\">Stay away from areas where water levels can rise rapidly, like storm drains, culverts, creeks and streams.&nbsp;</li><li dir=\"ltr\">If you are trapped in a building, move to the highest floor and call 911. Go to the roof only if necessary.&nbsp;</li><li dir=\"ltr\">Do not go into any room where electrical cords or outlets are under water. Stay out of water that may have electricity in it!</li><li dir=\"ltr\">If your vehicle is trapped in rapidly moving water, stay inside. If water is rising inside the vehicle, move to the roof and signal for help.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="wind chill warning",
            label="Wind Chill Warning",
            body="<p dir=\"ltr\">A Wind Chill Warning means that your area is experiencing strong winds and dangerously low temperatures. Take action to protect yourself and your loved ones from frostbite.&nbsp;</p><ul><li dir=\"ltr\">Stay indoors as much as possible.</li><li dir=\"ltr\">If you must go outside, dress in warm layers and cover every part of your body, including ears, nose, toes and fingers. Stay out of the wind as much as possible.&nbsp;</li><li dir=\"ltr\">Keep pets indoors, and lead livestock to shelter.&nbsp;</li><li dir=\"ltr\">When safe, check on older friends, family and neighbors to ensure they’re staying warm. &nbsp;&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="lake wind advisory",
            label="Lake Wind Advisory",
            body="<p>A Lake Wind Advisory means that strong winds are happening now or soon, and will cause rough waters on area lakes.&nbsp;</p><p>Boaters should use extra caution.</p>"
        )
        DynamicSafetyInformation.objects.create(
            type="dense smoke advisory",
            label="Dense smoke advisory",
            body="<p dir=\"ltr\">A Dense Smoke Advisory means that smoke is significantly reducing visibility in the area. Take precautions to stay safe:&nbsp;</p><ul><li dir=\"ltr\">If officials direct you to evacuate,&nbsp;<em><strong>do so immediately</strong></em>. Otherwise, stay indoors, and choose a room you can close off from outdoor air.&nbsp;</li><li dir=\"ltr\">Set your air system to “recirculate” mode, and close the outdoor intake.&nbsp;&nbsp;</li><li dir=\"ltr\">If you must go outside, wear a mask to avoid inhaling smoke.&nbsp;</li><li dir=\"ltr\">If driving, slow down, use your headlights, and leave plenty of distance ahead of you.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="rip current statement",
            label="Rip Current Statement",
            body="<p dir=\"ltr\">Rip currents may create dangerous swimming conditions in the area.&nbsp;&nbsp;</p><ul><li dir=\"ltr\">If you enter the water, always have a flotation device with you and swim near a lifeguard.&nbsp;</li><li dir=\"ltr\">Keep small children in sight and within arm’s reach at all times.&nbsp;</li><li dir=\"ltr\">If caught in a rip current, relax and float. Don’t swim against the current. If able, swim parallel to the shoreline.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="lake effect snow warning",
            label="Lake Effect Snow Warning",
            body="<p dir=\"ltr\">A Lake Effect Snow Warning means that your area can expect or is seeing localized heavy snow. These snow bands can create sudden drops in visibility, making driving conditions dangerous.&nbsp;&nbsp;</p><ul><li dir=\"ltr\">Avoid travel if possible. If you must travel, check road conditions and closures before you leave. Make sure you have an&nbsp;<a href=\"https://www.ready.gov/car\">emergency kit in your car</a>, and a full tank of gas and/or a fully charged battery.&nbsp;</li><li dir=\"ltr\">If stuck in your vehicle, stay there and contact the authorities for help. Run the motor about 10 minutes per hour for heat, but open the windows just a little for fresh air.&nbsp;</li><li dir=\"ltr\">Make sure that pets and other animals have plenty of food and water, and access to a warm shelter.</li><li dir=\"ltr\">If using heat from a fireplace or wood stove, make sure it is properly ventilated. Never use a gas range or oven to heat your home. If using a generator, it should be placed outdoors, at a distance from the home.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="beach hazards statement",
            label="Beach Hazards Statement",
            body="<p dir=\"ltr\">Your area may see dangerous swimming conditions. Use caution:&nbsp;</p><ul><li dir=\"ltr\">Stay off of rocks and jetties due to dangerous conditions</li><li dir=\"ltr\">Stay out of the water to avoid hazardous swimming conditions, and stay near occupied lifeguard towers&nbsp;</li><li dir=\"ltr\">Keep small children in sight and within arm’s reach at all times.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="flood advisory",
            label="Flood advisory",
            body="<p dir=\"ltr\">A Flood Advisory is issued when flooding may cause significant inconvenience, or even become dangerous if you are not careful. Know your risk at home, work and school, and use caution when flooding is expected.&nbsp;</p><ul><li dir=\"ltr\">Be aware of low-lying areas along your travel routes that are most likely to flood.&nbsp;</li><li dir=\"ltr\">Check road conditions before traveling, and obey road closures and barricades.&nbsp;</li><li dir=\"ltr\"><em><strong>Never</strong></em> walk, swim, or drive through flood waters.&nbsp;</li><li dir=\"ltr\">Stay tuned for local weather updates on the situation as it develops.</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="high surf warning",
            label="High Surf Warning",
            body="<p dir=\"ltr\">A High Surf Warning means that large, powerful waves pose a threat to life and property..&nbsp;</p><ul><li dir=\"ltr\">Stay out of the water - high surf conditions are not safe to swim or surf in.&nbsp;</li><li dir=\"ltr\">Stay away from the shoreline, and off of jetties and piers. Unpredictable waves can sweep people into the water.&nbsp;</li><li dir=\"ltr\">Be prepared for road closures in areas where surf may swamp low-lying roads.&nbsp;</li></ul>"
        )
        DynamicSafetyInformation.objects.create(
            type="high wind warning",
            label="High Wind Warning",
            body="<p dir=\"ltr\">A High Wind Warning means that dangerously strong winds are happening now or soon, and you should take immediate action to protect yourself and your property.&nbsp;</p><ul><li dir=\"ltr\">Take shelter now, and stay indoors if possible. Especially avoid being outside in forested areas or around large trees.&nbsp;</li><li dir=\"ltr\">Avoid driving if possible, as powerful cross winds create dangerous driving conditions, especially for high profile vehicles like vans, trucks and SUVs.&nbsp;</li><li dir=\"ltr\">If you must drive, slow down and keep both hands on the wheel. Keep your distance from high profile vehicles on the road.&nbsp;</li></ul>"
        )


    dependencies = [
        ('backend', '0005_load_initial_wfo_data'),
    ]

    operations = [
        migrations.RunPython(load_initial_dynamic_safety_info_data, delete_initial_dynamic_safety_info_data),
    ]
