# Generated by Django 5.2.8 on 2025-11-10 18:45

from django.db import migrations, models
from django.core import management

from pathlib import Path


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_update_dynamic_safety_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="wfo",
            name="ghwo_metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
