# Generated by Django 5.2.8 on 2025-11-13 18:27

from django.db import migrations
from django.core import management

from pathlib import Path


class Migration(migrations.Migration):
    def load_ghwo_metadata(apps, schema_editor):
        """Legacy.

        This migration previously loaded GHWO metadata into a ghwo_metadata column
        in the WFO table from a ghwo_metadata fixture file. That fixture file
        structure changed and the column was removed in 0014, so this migration
        would fail if we continued trying to load data with it. So the functionality
        has been removed without changing the structure of the migration so it
        will run properly, doing nothing.
        """
        pass

    dependencies = [
        ("backend", "0010_wfo_ghwo_metadata"),
    ]

    operations = [migrations.RunPython(load_ghwo_metadata)]
