# Generated by Django 5.2.8 on 2025-11-13 18:27

from django.db import migrations
from django.core import management

from pathlib import Path

class Migration(migrations.Migration):

    def load_ghwo_metadata(apps, schema_editor):
        """Loads the WFO fixtures that have ghwo metadata set on them."""
        fixtures_path = Path(Path(__file__).parent, "..", "fixtures")
        fixture_file_path = Path(fixtures_path, "ghwo_metadata.json")
        management.call_command("loaddata", str(fixture_file_path), verbosity=0)

    dependencies = [
        ('backend', '0010_wfo_ghwo_metadata'),
    ]

    operations = [
        migrations.RunPython(load_ghwo_metadata)
    ]
