# Generated by Django 5.2.8 on 2025-11-26 14:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0012_add_roadmap_page_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicsafetyinformation",
            name="body",
            field=wagtail.fields.RichTextField(),
        ),
    ]
