# Generated by Django 5.2.8 on 2025-12-01 20:15

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models
from pathlib import Path
import json


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_make_dynamicsafetyinformation_rich_text"),
    ]

    def unload_ghwo_metadata(apps, schema_editor):
        pass

    def load_ghwo_metadata(apps, schema_editor):
        HazardousWeatherOutlookMetadata = apps.get_model("backend", "HazardousWeatherOutlookMetadata")
        HazardousWeatherOutlookLevels = apps.get_model("backend", "HazardousWeatherOutlookLevels")
        WFO = apps.get_model("backend", "WFO")

        fixtures_path = Path(Path(__file__).parent, "..", "fixtures")
        fixture_file_path = Path(fixtures_path, "ghwo_metadata.json")

        with open(fixture_file_path) as f:
            metadata = json.load(f)

        for risk in metadata:
            standard = metadata[risk]["standard"]
            HazardousWeatherOutlookMetadata.objects.create(
                type=risk,
                basis=standard["basis"],
                wfo=None,
            )
            for number in standard["levels"]:
                level = standard["levels"][number]

                HazardousWeatherOutlookLevels.objects.create(
                    number=int(number),
                    label=level["label"],
                    description=level["description"],
                    type=risk,
                )

            custom = metadata[risk]["custom"]
            for office in custom["basis"]:
                HazardousWeatherOutlookMetadata.objects.create(
                    type=risk,
                    basis=standard["basis"],
                    wfo=WFO.objects.get(code=office),
                )
            for level in custom["levels"]:
                for office in custom["levels"][level]:
                    HazardousWeatherOutlookLevels.objects.create(
                        number=int(level),
                        label=custom["levels"][level]["label"] if "label" in custom["levels"][level] else "",
                        description=custom["levels"][level]["description"]
                        if "description" in custom["levels"][level]
                        else "",
                        wfo=WFO.objects.get(code=office),
                        type=risk,
                    )

    operations = [
        migrations.RemoveField(
            model_name="wfo",
            name="ghwo_metadata",
        ),
        migrations.CreateModel(
            name="HazardousWeatherOutlookLevels",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(blank=True, max_length=30)),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BlowingDust", "Blowing Dust Risk"),
                            ("CoastalFlood", "Coastal Flood Risk"),
                            ("ConvectiveWind", "Thunderstorm Wind Risk"),
                            ("ExcessiveRainfall", "Excessive Rainfall Risk"),
                            ("ExtremeCold", "Extreme Cold Risk"),
                            ("ExtremeHeat", "Extreme Heat Risk"),
                            ("FireWeather", "Fire Weather Risk"),
                            ("Fog", "Fog Risk"),
                            ("FreezingSpray", "Freezing Spray Risk"),
                            ("Frost/Freeze", "Frost/Freeze Risk"),
                            ("Hail", "Hail Risk"),
                            ("HighSurf", "High Surf Risk"),
                            ("IceAccumulation", "Ice Accumulation Risk"),
                            ("LakeshoreFlood", "Lakeshore Flood Risk"),
                            ("Lightning", "Lightning Risk"),
                            ("Marine", "Marine Hazard Risk"),
                            ("NonConvectiveWind", "Wind Risk"),
                            ("RipRisk", "Rip Current Risk"),
                            ("SevereThunderstorm", "Severe Thunderstorm Risk"),
                            ("SnowSleet", "Snow/Sleet Risk"),
                            ("SwimRisk", "Swim Risk"),
                            ("Tornado", "Tornado Risk"),
                        ],
                        max_length=256,
                    ),
                ),
                (
                    "wfo",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazardous_outlook_levels",
                        to="backend.wfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("type", "number", "wfo")},
            },
        ),
        migrations.CreateModel(
            name="HazardousWeatherOutlookMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BlowingDust", "Blowing Dust Risk"),
                            ("CoastalFlood", "Coastal Flood Risk"),
                            ("ConvectiveWind", "Thunderstorm Wind Risk"),
                            ("ExcessiveRainfall", "Excessive Rainfall Risk"),
                            ("ExtremeCold", "Extreme Cold Risk"),
                            ("ExtremeHeat", "Extreme Heat Risk"),
                            ("FireWeather", "Fire Weather Risk"),
                            ("Fog", "Fog Risk"),
                            ("FreezingSpray", "Freezing Spray Risk"),
                            ("Frost/Freeze", "Frost/Freeze Risk"),
                            ("Hail", "Hail Risk"),
                            ("HighSurf", "High Surf Risk"),
                            ("IceAccumulation", "Ice Accumulation Risk"),
                            ("LakeshoreFlood", "Lakeshore Flood Risk"),
                            ("Lightning", "Lightning Risk"),
                            ("Marine", "Marine Hazard Risk"),
                            ("NonConvectiveWind", "Wind Risk"),
                            ("RipRisk", "Rip Current Risk"),
                            ("SevereThunderstorm", "Severe Thunderstorm Risk"),
                            ("SnowSleet", "Snow/Sleet Risk"),
                            ("SwimRisk", "Swim Risk"),
                            ("Tornado", "Tornado Risk"),
                        ],
                        max_length=256,
                    ),
                ),
                ("basis", wagtail.fields.RichTextField()),
                (
                    "wfo",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazardous_outlook_metadata",
                        to="backend.wfo",
                    ),
                ),
            ],
            options={
                "unique_together": {("type", "wfo")},
            },
        ),
        migrations.RunPython(load_ghwo_metadata, unload_ghwo_metadata),
    ]
