# Generated by Django 5.2.9 on 2025-12-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0014_remove_wfo_ghwo_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpage",
            name="meta_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roadmappage",
            name="meta_description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
