# Generated by Django 5.2.9 on 2026-01-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0015_add_custom_meta_description_to_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapentry",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roadmapentry",
            name="delivery_date",
            field=models.DateField(null=True),
        ),
    ]
