# Generated by Django 5.2.9 on 2026-01-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_add_delivered_flag_to_roadmap_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roadmapentry",
            name="delivery_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
