# Generated by Django 6.0.5 on 2026-08-13 19:11

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("backend", "0017_default_roadmap_entry_delivery_date_to_none"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HazardGuideIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("content", models.TextField(blank=True, help_text="Intro text for the index page.")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HazardGuidePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("meta_description", models.TextField()),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text=
                            "Optional alt text for the hero image. If not set, will be default to the image title.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HazardGuideSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("header", models.CharField(max_length=255)),
                ("content", wagtail.fields.RichTextField(blank=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("other", "Other"),
                            ("before", "Before - only add one per page"),
                            ("during", "During - only add one per page"),
                            ("after", "After - only add one per page"),
                            ("alerts", "Alerts - only add one per page"),
                            ("resources", "Resources - only add one per page"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="backend.hazardguidepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HazardLevelEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[("other", "Other"), ("watch", "Watch"), ("warning", "Warning")], max_length=10
                    ),
                ),
                (
                    "alert_text",
                    models.TextField(
                        help_text="The name of the hazard alert (i.e. Tornado Advisory, Tornado Warning)."
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        help_text=
                            "The description of the hazard level, including what it means and what actions to take."
                    ),
                ),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazard_level_entries",
                        to="backend.hazardguidesection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResourceLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("text", models.CharField(max_length=255, verbose_name="Display text")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="The URL of the resource. Use the full URL (i.e. https://www.example.com/path/to/resource/).",
                        verbose_name="Link url",
                    ),
                ),
                (
                    "section",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_links",
                        to="backend.hazardguidesection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
