# Generated by Django 6.0.2 on 2026-02-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_default_roadmap_entry_delivery_date_to_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapentry',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
