# Generated by Django 6.0.5 on 2026-09-01 20:49

from django.db import migrations
from wagtail.documents import get_document_model
from wagtail.images import get_image_model
from wagtail.models import Collection

DEFAULT_STATE_NAMES = [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Fed States of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Virgin Islands",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]


def _get_state_names(apps):
    """Get state names from WeatherStates if available, else use defaults."""
    WeatherStates = apps.get_model("spatial", "WeatherStates")
    state_names = list(
        WeatherStates.objects.exclude(name__isnull=True)
        .exclude(name__exact="")
        .values_list("name", flat=True)
        .order_by("name")
    )

    return state_names or DEFAULT_STATE_NAMES


def _ensure_child(parent, name):
    """Return an existing child collection or create it if missing."""
    existing_child = parent.get_children().filter(name=name).first()
    return existing_child or parent.add_child(name=name)


def _ensure_wagtail_groups(apps, group_prefix="MST", collection=None):
    # Get models using historical versions
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    GroupCollectionPermission = apps.get_model("wagtailcore", "GroupCollectionPermission")

    # 1. Create the Group based on the collection passed in
    editor_group, created = Group.objects.get_or_create(name=f"{group_prefix}-Contributors")
    admin_group, created = Group.objects.get_or_create(name=f"{group_prefix}-Admins")

    # 2. Grant Access to Wagtail Admin Dashboard
    admin_permission, _ = Permission.objects.get_or_create(
        content_type__app_label="wagtailadmin", codename="access_admin"
    )
    editor_group.permissions.add(admin_permission)
    admin_group.permissions.add(admin_permission)

    # 4. Assign Collection Permissions (+Images and Documents)
    if collection:
        # Fetch the base permission objects required for Collections
        collection_content_type = ContentType.objects.get_for_model(Collection)

        # Wagtail uses standard Django permissions linked to Collections via GroupCollectionPermission
        for codename in ["add_collection"]:
            perm, _ = Permission.objects.get_or_create(content_type=collection_content_type, codename=codename)
            GroupCollectionPermission.objects.get_or_create(
                group=editor_group, collection_id=collection.pk, permission=perm
            )
            GroupCollectionPermission.objects.get_or_create(
                group=admin_group, collection_id=collection.pk, permission=perm
            )

        # Get the content type for Wagtail images
        image_content_type = ContentType.objects.get_by_natural_key("wagtailimages", "image")

        root_collection = Collection.get_first_root_node()
        # All groups get "choose_image" permissions for all images
        for codename in ["choose_image"]:
            permission = Permission.objects.get(content_type=image_content_type, codename=codename)
            GroupCollectionPermission.objects.get_or_create(
                group=editor_group,
                collection_id=root_collection.pk,
                permission=permission,
            )
            GroupCollectionPermission.objects.get_or_create(
                group=admin_group,
                collection_id=root_collection.pk,
                permission=permission,
            )

        # Now add the add/edit image permissions for the collection
        for codename in ["add_image", "change_image"]:
            permission = Permission.objects.get(content_type=image_content_type, codename=codename)
            GroupCollectionPermission.objects.get_or_create(
                group=editor_group,
                collection_id=collection.pk,
                permission=permission,
            )
            GroupCollectionPermission.objects.get_or_create(
                group=admin_group,
                collection_id=collection.pk,
                permission=permission,
            )


def create_nested_collections(apps, _schema_editor):
    """Create required nested collection for every state and WFO."""
    WFO = apps.get_model("backend", "WFO")
    root_collection = Collection.get_first_root_node()
    states_collection = _ensure_child(root_collection, "States")

    for state_name in _get_state_names(apps):
        state_coll = _ensure_child(states_collection, state_name)
        # Add permissions for the new state collection.
        _ensure_wagtail_groups(apps, state_name, state_coll)
        # Add child collections under the state collection.
        # Permissions are inherited
        _ensure_child(state_coll, "Event Recaps")
        _ensure_child(state_coll, "General Photos")

    wfos_collection = _ensure_child(root_collection, "WFOs")
    for wfo_code, wfo_name in WFO.objects.order_by("code").values_list("code", "name"):
        wfo_coll = _ensure_child(wfos_collection, f"{wfo_code} - {wfo_name}")
        # Add permissions for the new WFO collection.
        _ensure_wagtail_groups(apps, wfo_code, wfo_coll)
        # Add child collections - permissions are inherited
        _ensure_child(wfo_coll, "Community Outreach")
        _ensure_child(wfo_coll, "General Photos")


def _holds_media(collection):
    """Whether any image or document lives in this collection or below it."""
    # Image.collection and Document.collection are on_delete=CASCADE, so deleting
    # a collection destroys the uploads inside it rather than moving them to root.
    collection_ids = list(collection.get_descendants(inclusive=True).values_list("id", flat=True))

    return (
        get_image_model().objects.filter(collection_id__in=collection_ids).exists()
        or get_document_model().objects.filter(collection_id__in=collection_ids).exists()
    )


def _remove_child(parent, name):
    """Delete a named child collection and its subtree, unless it holds uploads."""
    child = parent.get_children().filter(name=name).first()
    if child and not _holds_media(child):
        child.delete()


def _remove_if_empty(collection):
    """Delete a collection only when this migration left nothing behind in it."""
    if collection and not collection.get_children().exists() and not _holds_media(collection):
        collection.delete()


def _remove_wagtail_groups(apps, group_prefix="MST"):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__startswith=group_prefix).delete()


def remove_nested_collections(apps):
    """Delete nested collections, but only after checking if they hold images."""
    WFO = apps.get_model("backend", "WFO")
    root_collection = Collection.get_first_root_node()

    # Remove only the collections created by this migration, leaving any
    # editor-added siblings (and the images they hold) untouched.
    states_collection = root_collection.get_children().filter(name="States").first()
    if states_collection:
        for state_name in _get_state_names(apps):
            state_coll = states_collection.get_children().filter(name=state_name).first()
            if state_coll:
                _remove_child(state_coll, "Event Recaps")
                _remove_child(state_coll, "General Photos")
                _remove_if_empty(state_coll)
                _remove_wagtail_groups(apps, group_prefix=state_name)
        _remove_if_empty(states_collection)

    wfos_collection = root_collection.get_children().filter(name="WFOs").first()
    if wfos_collection:
        for wfo_code, wfo_name in WFO.objects.order_by("code").values_list("code", "name"):
            wfo_coll = wfos_collection.get_children().filter(name=f"{wfo_code} - {wfo_name}").first()
            if wfo_coll:
                _remove_child(wfo_coll, "Community Outreach")
                _remove_child(wfo_coll, "General Photos")
                _remove_if_empty(wfo_coll)
                _remove_wagtail_groups(apps, group_prefix=wfo_code)
        _remove_if_empty(wfos_collection)


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ("backend", "0005_load_initial_wfo_data"),
        ("backend", "0018_hazardguideindexpage_hazardguidepage_and_more"),
        ("spatial", "0005_weatherstates"),
    ]

    operations = [
        migrations.RunPython(create_nested_collections, remove_nested_collections),
    ]
