# Generated by Django 6.0.5 on 2026-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101

    dependencies = [
        ("backend", "0018_hazardguideindexpage_hazardguidepage_and_more"),
        ("backend", "0019_create_cms_collections"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hazardlevelentry",
            old_name="alert_text",
            new_name="alert_title",
        ),
        migrations.AlterField(
            model_name="hazardlevelentry",
            name="alert_level",
            field=models.CharField(choices=[
                ("other", "Other (Advisory, Special Weather Statement, etc.)"),
                ("watch", "Watch"),
                ("warning", "Warning/Emergency")
                ],
                max_length=10),
        ),
        migrations.AlterField(
            model_name="resourcelink",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="The full URL (i.e. https://www.example.com/path/to/resource/), "
                + "or the path if an internal beta.weather.gov page.",
                max_length=255,
                verbose_name="Link url"),
        ),
    ]
