# Generated by Django 6.0.8 on 2026-09-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_rename_alert_text_hazardlevelentry_alert_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='meta_description',
            field=models.TextField(max_length=155),
        ),
        migrations.AlterField(
            model_name='hazardguidepage',
            name='meta_description',
            field=models.TextField(max_length=155),
        ),
        migrations.AlterField(
            model_name='roadmappage',
            name='meta_description',
            field=models.TextField(max_length=155),
        ),
    ]
