# Generated by Django 6.0.8 on 2026-09-30 13:58

from django.db import migrations


def create_viewers_group(apps, _):  # noqa: D103
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    viewers_group, _ = Group.objects.get_or_create(name="Viewers")
    viewers_perm, _ = Permission.objects.get_or_create(
        content_type__app_label="wagtailadmin", codename="access_admin")
    viewers_group.permissions.add(viewers_perm)

def remove_viewers_group(apps):  # noqa: D103
    Group = apps.get_model("auth", "Group")
    viewers_group = Group.objects.get(name="Viewers")
    viewers_group.delete()

class Migration(migrations.Migration):  # noqa: D101

    dependencies = [
        ("backend", "0021_alter_genericpage_meta_description_and_more"),
    ]

    operations = [
        migrations.RunPython(create_viewers_group, remove_viewers_group)
    ]
