"""
Django settings for weathergov project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import subprocess
from pathlib import Path

import environs
from cfenv import AppEnv  # type: ignore

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environs.Env()

# Get secrets from Cloud.gov user provided service, if exists
# If not, get secrets from environment variables
key_service = AppEnv().get_service(name="test-credentials") # for weathergov-test
rds_service = AppEnv().get_service(name="weathergov-rds-test")

if key_service and key_service.credentials:
    secret = key_service.credentials.get
else:
    secret = env

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
secret_key = secret("django_secret_key")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret_key

# SECURITY WARNING: don't run with debug turned on in production!
env_debug = env.bool("DJANGO_DEBUG", default=False)
DEBUG = env_debug

ALLOWED_HOSTS = [
    "weathergov-test.app.cloud.gov",
]

ALLOWED_CIDR_NETS = ["10.0.0.0/8"]

# For request paths without a trailing slash, add one automatically to resolve
# the handler. This is True by default, but let's set it explicitly to be...
# explicit.
APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    "backend",
    "spatial",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Wagtail dependencies
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
]

MIDDLEWARE = [
    # django-allow-cidr: enable use of CIDR IP ranges in ALLOWED_HOSTS
    "allow_cidr.middleware.AllowCIDRMiddleware",
    # serve static assets in production
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    # Wagtail related middleware
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "backend.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "backend.context_processors.route_info",
            ],
            "builtins": [
                "django.templatetags.i18n",
                "django.templatetags.static",
                "backend.templatetags.weather_i18n",
                "backend.templatetags.weather_partials",
                "backend.templatetags.util",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.config.wsgi.application"

def find_cloudgov_library(name):
    """
    Find the cloud.gov apt installed library.

    In cloud.gov, buildpacks install their dependencies in
    `/home/vcap/deps`; since the apt buildpack is configured to run first, we
    search in `/home/vcap/deps/0/lib` for the libraries we need. (`/1` is
    for the python buildpack, which runs second)
    """
    apt_library_dir = "/home/vcap/deps/0/lib"
    ls_output = subprocess.run(["/bin/ls", "-1", apt_library_dir], check=True, capture_output=True) # noqa: S603 (no untrusted input)
    ls_list = ls_output.stdout.decode("utf8").split("\n")
    lib_entry = [entry for entry in ls_list if entry.strip().startswith(name)]
    if lib_entry:
        return f"{apt_library_dir}/{lib_entry[0].strip()}"
    return None

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if rds_service and rds_service.credentials:
    db_credentials = rds_service.credentials
    # NB: Jammy (Ubuntu LTS) has slightly older versions than in our images.
    # GEOS_LIBRARY_PATH = "/home/vcap/deps/0/lib/libgeos_c.so.1"
    # GDAL_LIBRARY_PATH = "/home/vcap/deps/0/lib/libgdal.so.30"
    GEOS_LIBRARY_PATH = find_cloudgov_library("libgeos")
    GDAL_LIBRARY_PATH = find_cloudgov_library("libgdal")
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": db_credentials["name"],
            "USER": db_credentials["username"],
            "PASSWORD": db_credentials["password"],
            "HOST": db_credentials["host"],
            "PORT": db_credentials["port"],
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.contrib.gis.db.backends.postgis",
            "NAME": os.environ.get("POSTGRES_DB"),
            "USER": os.environ.get("POSTGRES_USER"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
            "HOST": "database",
            "PORT": 5432,
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"
# LANGUAGES = (
#     ("en", _(u"English")),
#     ("es", _(u"Spanish")),
#     ("zh-hans", _(u"Chinese"))
# )

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# URL to use when referring to static files located in STATIC_ROOT
# Must be relative and end with "/"
STATIC_URL = "public/"

STATIC_ROOT = BASE_DIR / "frontend" / "public"

STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "assets",
]


# Wagtail related settings
# See https://docs.wagtail.org/en/stable/getting_started/integrating_into_django.html
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

WAGTAIL_SITE_NAME = "beta.weather.gov"
WAGTAILADMIN_BASE_URL = "http://localhost:8080"  # Change to env variable for config
WAGTAILDOCS_EXTENSIONS = ["jpg", "jpeg", "pdf", "png", "gif"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# i18n
LOCALE_PATHS = [BASE_DIR / "locale"]

# Custom site information
SITE_LOGO = "/public/logo.svg"
SITE_NAME = "beta.weather.gov"
SITE_SLOGAN = "National Weather Service"

# region: Logging-----------------------------------------------------------###

# A Python logging configuration consists of four parts:
#   Loggers
#   Handlers
#   Filters
#   Formatters
# https://docs.djangoproject.com/en/4.1/topics/logging/

# Log a message by doing this:
#
#   import logging
#   logger = logging.getLogger(__name__)
#
# Then:
#
#   logger.debug("We're about to execute function xyz. Wish us luck!")
#   logger.info("Oh! Here's something you might want to know.")
#   logger.warning("Something kinda bad happened.")
#   logger.error("Can't do this important task. Something is very wrong.")
#   logger.critical("Going to crash now.")


LOGGING = {
    "version": 1,
    # Don't import Django's existing loggers
    "disable_existing_loggers": True,
    # define how to convert log messages into text;
    # each handler has its choice of format
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            "datefmt": "%d/%b/%Y %H:%M:%S",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
    },
    # define where log messages will be sent
    # each logger can have one or more handlers
    "handlers": {
        "console": {
            "level": os.environ.get("DJANGO_LOG_LEVEL", "DEBUG"),
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        # No file logger is configured,
        # because containerized apps
        # do not log to the file system.
    },
    # define loggers: these are "sinks" into which
    # messages are sent for processing
    "loggers": {
        # Django's generic logger
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's template processor
        "django.template": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's runserver
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        # Django's runserver requests
        "django.request": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        # Our app!
        "weather": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    # root logger catches anything, unless
    # defined by a more specific logger
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# endregion

if DEBUG:
    # used by debug() context processor
    INTERNAL_IPS = [
        "127.0.0.1",
        "::1",
    ]

    # allow dev laptop and docker-compose network to connect
    ALLOWED_HOSTS += ("localhost", "web", "0.0.0.0") # noqa: S104 (DEBUG is never turned on in prod)
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "localhost"
