name: ADR created
on:
  issues:
    types:
      - closed

jobs:
  main:
    name: ADR created
    runs-on: ubuntu-latest

    # Only run this workflow if the closed issue has
    if: "${{ contains(github.event.issue.labels.*.name, 'ADR') && contains(github.event.issue.labels.*.name, 'ADR: approved') }}"

    steps:
      - run: echo "bob"
